### ISSUE TITLE
How to query event types (Documentation request)

### ISSUE THREAD

**Issue by anchovy** [verbb/Events#101]
**What are you trying to do?**
Programatically list the different event types in a twig template.
We've got a front end form allowing users to add events and we need them to select the event type.
Looking at the docs, I can see any examples where you can query/list theses.
(https://verbb.io/craft-plugins/events/docs/feature-tour/event-types)

We're currently hard coding the select box with the event type id, but this is extremely brittle!

**What's your proposed solution?**
Documentation on how to query the event types.

**Comment by engram-design** [comment]
For the moment, you can use `craft.events.getEventTypes()` or `craft.events.getEditableEventTypes()` to loop through [event type models](https://github.com/verbb/events/blob/craft-3/src/models/EventType.php), but yes there's no documentation on the model.
