### ISSUE TITLE
Missing ability to define a SKU on Events?

### ISSUE THREAD

**Issue by MattWilcox** [verbb/Events#102]
In the Receipt code, it's easy to output the SKU for both the Event and the Ticket, like this:

```
{% for item in order.lineItems %}
    {# The Event details... #}
    {{ item.description }}
    {{ item.sku }}

    {# The Ticket Details... #}
    {% if craft.events.isTicket( item ) %}{# https://verbb.io/craft-plugins/events/docs/template-guides/cart-order #}
        {% set ticket = item.purchasable %}
        {% for purchasedTicket in ticket.getPurchasedTickets(item) %}
            Ticket SKU: {{ purchasedTicket }}
        {% endfor %}
    {% endif %}
{% endfor %}
```

However i've realised that unlike a normal Purchasable in Commerce, Events can not have their SKU set (or apparently shown in the GUI anyway) - they seem to be treated as just Entries despite being Purchasable?

In fact, the Model for Events doesn't include a SKU: https://verbb.io/craft-plugins/events/docs/v0/models/event-model

This is a problem because we're using the Xero plugin to try and match the inventory the client has in their Xero account to the Event we're selling tickets for; and there's no way to see the generated SKU for the Event, or more importantly to explicitly set the SKU for the Event in Craft to match the existing SKU in the client's Xero infrastructure.

Would it be possible to expose the standard SKU stuff that Purchasable have in the Events GUI in the CMS?

Or is there some other method for us to be able to do this?

We're a little stuck on what we can send to Xero as the plugin doesn't let us set things, it just sends the following fields: https://github.com/moacode/commerce-xero/blob/master/README.md#what-fields-are-sent-to-xero

Which, we think, should include the Event SKU as opposed to the Ticket SKU?

**Additional info**
![puchesable](https://user-images.githubusercontent.com/814039/173831738-1fc0c939-9204-42ae-9411-79386575d72e.jpg) vs 
![event](https://user-images.githubusercontent.com/814039/173831745-c2b2964e-8ff1-4f4f-b35e-7c4a3eceb788.jpg)

- Plugin version: 1.4.20
- Craft version: 3.7.44
- Multi-site: No

**Comment by MattWilcox** [comment]
PS: It may be that we're thinking of this backward and we need to add a cutom field on the Event that matches the Xero SKU, then edit the Xero plugin to somehow send the Event SKU... Please let me know if that sounds "more correct", as what we have in that receipt code - while it works to output an Event SKU that's in the system - seems a bit weird.

**Comment by engram-design** [comment]
So events are the purchasable "thing" it's technically the event's tickets that are, and those have an SKU. In the same way that a Commerce Product doesn't have an SKU directly, but a Variant does, the same relationship is with Events and Tickets. And yes, I know for products with no variants, the UI shows that you can enter a SKU, but technically this is for a single Variant (the default variant).

But the issue still stands, and I agree there's no UI for you to define what the SKU for tickets are, and they are in fact [auto-generated](https://github.com/verbb/events/blob/c70c826b4b95eddd34e99221ea5bf1d982856cb0/src/elements/Event.php#L652)

Now a Purchased Ticket SKU is also a different to a Ticket SKU, and is also [generated](https://github.com/verbb/events/blob/c70c826b4b95eddd34e99221ea5bf1d982856cb0/src/elements/Ticket.php#L494) but that will always be the case, as that's essentially the "ID" of a purchased ticket when someone makes a ticket purchase. As such, these can't be "set" as they're generated upon checkout.

A redesigned UI will be likely bundled into Events v2 changes https://github.com/verbb/events/issues/75 which will be more Commerce-like.

I can't say I'm familiar with the Xero plugin, but I would've thought there be an event or similar for you to hook in to what gets sent to them, so you could tweak the Ticket information (the thing that people purchase) to add things like the parent Event info, or other things about tickets.

**Comment by MattWilcox** [comment]
Cheers for the fast response. That all does make sense - I think I was understanding things more-or-less properly then. The fact we can "get a SKU for the Event" is just cruft from extending Commerce stuff, and we need to fiddle with the Xero integration instead.

Yeah, it's our first time working with Xero, and the plugin does look to be undeveloped at the moment :/

**Comment by engram-design** [comment]
I'll mention that events have no SKU, and looking at your template, `{{ item.sku }}` is still the Ticket element SKU, and further down `{{ purchasedTicket }}` technically is the Purchased Ticket element SKU (different) - but just wanted to clarify that an Event element certainly doesn't have an SKU.

But as mentioned, yep - we'll certainly be adding that to our updated UI for you to manage!

**Comment by MattWilcox** [comment]
Ok, so `{{ item.sku }}` would be identical over all tickets of that type sold, and `{{ purchasedTicket }}` is the SKU for the individual ticket the customer purchased? But in either case, we can not set a SKU manually (and nor should we for the purchasedTicket as that needs to be unique).

Thanks again.
