### ISSUE TITLE
Can not install Events plugin - Craft CMS 3.7.45.2 due to jsvrcek/ics ^0.7.0 and no PHP8 support

### ISSUE THREAD

**Issue by webvader** [verbb/Events#104]
Can not install the plugin. I get an error on installation:

```
Problem 1
- verbb/events 1.4.20 requires jsvrcek/ics ^0.7.0 -> satisfiable by jsvrcek/ics[0.7].
- jsvrcek/ics 0.7 requires php ^5.4 || ^7.0 -> your php version (8.1; overridden via config.platform, actual: 8.1.6) does not satisfy that requirement.
- Root composer.json requires verbb/events 1.4.20 -> satisfiable by verbb/events[1.4.20].
```

The dependency of jsvrcek/ics has to be updated to ^0.8.0 for PHP8 compatibility. In the Craft CMS 4 plugin this is done but not in the Craft CMS 3 version.

**Steps to reproduce**
1. Install plugin via CP or CLI

**Additional info**
- Plugin version: 1.4.20
- Craft version: 3.7.45.2

**Comment by engram-design** [comment]
Fixed in [1.4.21](https://github.com/verbb/events/releases/tag/1.4.21)
