### ISSUE TITLE
Deleting commerce order - tickets still valid

### ISSUE THREAD

**Issue by anchovy** [verbb/Events#107]
### Describe the bug

Deleting the commerce order doesn't delete the ticket and the QR code is still valid.

1. When the related commerce order is deleted/cancelled the associated tickets in the event plugin are not touched - they are still listed as purchased tickets.
2. The QR code for an event with a deleted commerce order still checks the user in.

### Steps to reproduce

<h2>Issue 1 - ticket not deleted</h2>

1. Create an event with at least 1 ticket type
2. Purchase a ticket
3. Delete the order in Commerce
4. View tickets for the event - still shows the ticket
![image](https://user-images.githubusercontent.com/599005/189765796-2bafb31e-801f-469e-b816-a3ab13ffc6fd.png)
5. Purchased Tickets Summary on the event still shows the ticket quantity.

**Expected outcome**
- I'd expect the ticket to be trashed but all it's got is '[Deleted order]'.
- I'd expect the 'Purchased Tickets Summary' count on the event to decrease by 1.
- If the ticket had already been checked in - I'd expect the order to be able to be deleted, but maybe with a warning/alert that the ticket had already been checked.

<h2>Issue 2 - ticket is still valid</h2>

1. Imagine user still has the QR code for the ticket supplied before the commerce order was deleted.
2. User attends event and scans QR code.
3. QR Code scans successfully
![Screenshot 2022-09-13 at 9 58 47 AM](https://user-images.githubusercontent.com/599005/189766508-1ea3f0c4-81a8-4ec4-92f2-0b171d799352.png)

**Expected outcome**
- I'd expect the check in to fail because the order was no longer valid and therefore the ticket was deleted.
- i.e. 
<img width="268" alt="image" src="https://user-images.githubusercontent.com/599005/189768709-4e6be2a5-17d9-427b-90b2-8b5c3f931258.png">

### Craft CMS version

Craft Pro 3.7.53.1

### Plugin version

1.4.22

### Multi-site?

No

### Additional context

There's the issue of what to do when a checked in ticket order is deleted in commerce - I think a simple warning that the ticket associated with the order has already been checkin should work?

**Comment by engram-design** [comment]
In the same way that Commerce doesn't restore stock for a deleted, cancelled or refunded order, we don't either. I can see the argument that once an order is deleted, any associated tickets should be as well, but it get's tricky if that order is restored (after being soft-deleted), dealing with capacities, etc.

The other issue is that purchased tickets can be created without a related order, which is still okay to have their QR code used. There's no real way of telling if there's never been an order associated with a purchased ticket (manually created), or if there was, and the order has just been deleted. So disabling checking in if there's no order associated with the purchased ticket get's tricky without adding more more handling for flagging manually-created purchased tickets, or tracking deleted-order purchased tickets. Although if we end up trashing purchased tickets, none of that will matter.

It'd be great to have a warning when deleting the order for any checked-in tickets, but that likely won't be possible. That's also a bit of a grey area I think. Does a deleted order actually mean a refund? Does your client actually offer refunds for tickets once checked in? A few cases to consider.

I'll see what we can do.

**Comment by engram-design** [comment]
Updated in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
