### ISSUE TITLE
Add attendees view, to see a list of customers with tickets

### ISSUE THREAD

**Issue by engram-design** [verbb/Events#11]

**Comment by KatieMFritz** [comment]
Yes please!! Timeline on this?

**Comment by engram-design** [comment]
No ETA but our next todo item will be to show purchased tickets and their information. Will keep you posted.

**Comment by KatieMFritz** [comment]
Hi Josh! Any updates on this?

**Comment by KatieMFritz** [comment]
How are people working around this? Custom frontend code to generate an attendees list?

**Comment by engram-design** [comment]
Added in [1.2.0](https://github.com/verbb/events/releases/tag/1.2.0)

**Comment by engram-design** [comment]
Its not an attendees view, but its just as good! I've added customer information into the purchased tickets element index, and you can toggle on those columns to see that info. You can also filter these via events, so its a good attendees view.

See [1.4.0](https://github.com/verbb/events/releases/tag/1.4.0)
