### ISSUE TITLE
Ability to Add Time Zone Per Event

### ISSUE THREAD

**Issue by RitterKnightCreative** [verbb/Events#110]
### What are you trying to do?

Client often has trainings in multiple states/time zones so the ability to add a time zone per event is handy. 

We worked around the problem with a dropdown on the General tab but it's not the appropriate place for it.

### What's your proposed solution?

Would be nice to see a dropdown in the Dates/Times tab for choosing which time zone and defaulting to the time zone of the site.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
