### ISSUE TITLE
Deleting tickets sets the 'Total Capacity' to 0

### ISSUE THREAD

**Issue by anchovy** [verbb/Events#114]
### Describe the bug

When adding/editing an event, if I delete all the tickets the Total Capacity is set to 0.
If a user then adds a new ticket, they also need to update the Total Capacity to be empty or a new number.

Believe this is occurring in the `sumAllQuantities` js function.

I believe the total capacity should be totally separate from the ticket Quantity. You might have an online event with unlimited capacity but you want to have a ticket type of Premium with a limit of 200. Technically this function would set the total capacity to 200.

### Steps to reproduce

1. Add/edit an event
2. Goto the Tickets tab
3. The default Total Capacity field value is empty.
4. Add a ticket
5. Delete the ticket
6. Note the Total Capacity field value is now set to 0.

NB - this function only seems to be called when a ticket is deleted. If I then added another ticket (with or without a ticket quantity) the Total Capacity is not changed, it's still set to 0.

### Craft CMS version

Craft Pro 3.7.55.3

### Plugin version

1.4.23

### Multi-site?

No

**Comment by engram-design** [comment]
The only way I'm seeing this, is if the "Total Capacity" is empty, and you delete all the tickets. The capacity will be set to 0.

The capacity of an event should be independent of the ticket quantities. The only case where it will populate the total capacity is if that's empty. For example, you skip setting the capacity, and create your tickets with the quantity. It'd be useless to have an event with 0 capacity, while having tickets available for purchase - but you can't buy any with a 0 capacity.

Is this the behaviour that is an issue for you?

**Comment by anchovy** [comment]
Yep / that's what's happening. I can see instances where an admin creates/edits an event and adds a ticket, realises its the wrong ticket type and rather than change the ticket type deletes the ticket and adds a new one - not realising that the total capacity has been automagically set to 0. 

Also, in our case, we have a ticket type that will never have a max capacity so we'll never want a max capacity of 0.

I could understand if the default capacity was 0 and there was a toggle for enforcing max capacity, but there isn't, so this value shouldn't be arbitrary set when all tickets have been deleted. Also,the notes say something like this is limit is independent of the individual ticket quantities, so again shouldn't be set based on a ticked change/deletion.

(Sorry for the rambling notes!)

**Comment by engram-design** [comment]
Fair enough, I'll give this some thought. I just wanted to check as I couldn't replicate it with a value set in the total capacity field, when adding or deleting tickets.

**Comment by engram-design** [comment]
Updated in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
