### ISSUE TITLE
QR generation error

### ISSUE THREAD

**Issue by dimetechgroup** [verbb/Events#117]
### Describe the bug

On updating to the latest version, getting
`Too few arguments to function Endroid\QrCode\QrCode::__construct()`

### Steps to reproduce

1. Update Craft
2. Update events
3. 

### Craft CMS version

4.3.6.1

### Plugin version

2.0.0-beta.8

### Multi-site?

No

### Additional context

This happens due to outdated call to endroid/qrcode in getQrCode() method of PurchasedTicket element type

I solved it using the code below:

```
public function getQrCode(): string
    {
        $url = UrlHelper::actionUrl('events/ticket/checkin', ['sku' => $this->ticketSku]);
		
		$writer = new PngWriter();

		// Create QR code
		$qrCode = QrCode::create($url)
			//->setEncoding(new Encoding('UTF-8'))
			->setErrorCorrectionLevel(new ErrorCorrectionLevelMedium())
			->setSize(300)
			->setMargin(10)
			->setRoundBlockSizeMode(new RoundBlockSizeModeMargin())
			->setForegroundColor(new Color(0, 0, 0))
			->setBackgroundColor(new Color(255, 255, 255));


		$result = $writer->write($qrCode);

        return $result->getDataUri();
    }
```

**Comment by engram-design** [comment]
Fixed for the next release - we're still updating a few things like the QR code dependancy. To get the fix early, change your `verbb/events` requirement in `composer.json` to:

```
"require": {
  "verbb/events": "dev-craft-4 as 2.0.0-beta.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Updated in [2.0.0-beta.9](https://github.com/verbb/events/releases/tag/2.0.0-beta.9)
