### ISSUE TITLE
Uncaught error when saving an event with a ticket with empty fields

### ISSUE THREAD

**Issue by MoritzLost** [verbb/Events#121]
### Describe the bug

When an event is saved that includes a ticket row with an empty _Ticket Type_ or _Price_ field, you get an uncaught error with no opportunity to fix the issue:

![variable-tickettype-does-not-exist](https://user-images.githubusercontent.com/10146880/221904508-662a354b-9eed-415a-85f7-56012f1550a0.png)

![ticket-price-error](https://user-images.githubusercontent.com/10146880/221905229-835a8348-7fdf-4cc5-9470-517f8ea0a9e6.png)

Instead of resulting in a server error, this should just show a validation error in the edit form, allowing the user to fix the issue.

### Steps to reproduce

1. Create a new event.
2. In the _Tickets_ tab, click on _Add ticket_.
3. Leave the _Ticket Type_ and/or _Price_ fields empty and save the event.

### Craft CMS version

4.3.10

### Plugin version

2.0.0-beta.8

**Comment by engram-design** [comment]
Updated in [2.0.0-beta.9](https://github.com/verbb/events/releases/tag/2.0.0-beta.9)
