### ISSUE TITLE
Title field appears in every tab for event types

### ISSUE THREAD

**Issue by mihob** [verbb/Events#125]
### Describe the bug

When editing event types, the title field appears in every tab, which is somewhat irritating. Would it be possible to handle this in the same way as with normal entries? Or only display the title field in the first tab?

### Steps to reproduce

1.  Create a new event type
2. Assign several fields to this event type in different tabs

### Craft CMS version

Craft Pro 4.5.10

### Plugin version

2.0.1

**Comment by engram-design** [comment]
Updated in [2.0.2](https://github.com/verbb/events/releases/tag/2.0.2)
