### ISSUE TITLE
Tickets only available in the control panel

### ISSUE THREAD

**Issue by mihob** [verbb/Events#126]
### Question

Is it possible to create tickets that can only be "ordered" via the Control Panel? 

The background to this is that we have ticket types that are free of charge and should only be created by admins.

However, if you set a ticket to unavailable (either by the time period or by the number), you cannot select it when placing an order in the control panel.

**Comment by engram-design** [comment]
What about just not rendering any of the event types on the front end of your site that people can purchase? If people can’t find them, then they can’t be purchased.

Or, if you’d like just some events to not be purchasable on the front end, I’d create a custom field like a light switch on the event type for you to manage this visibility. You can then factor that into your front end rendering query.

```twig
{% for event in craft.events.myVisibilityField(true).all() %}
```

Which would fetch all events where the `myVisibilityField` is enabled.

**Comment by mihob** [comment]
Thank you for your feedback. However, it is not about different events but about different tickets or ticket types for one event.  

For example, we have the following tickets for an event:
Normal - 100$
Student - 50$
VIP - 0$

VIP tickets should not appear in the frontend or be purchasable. 

I realise that you can simply hide certain tickets. However, if someone knows the ID of the ticket article, it would still be possible to purchase a "free" ticket by manipulating the forms.

**Comment by engram-design** [comment]
Right, I see what you mean, sorry!

So that's a similar approach (adding a field/check to the ticket type), but there would be no enforcement on it, so it would be open to abuse like you mention.

So nothing in the works regarding that at the moment, but we'll add it to the list.

**Comment by engram-design** [comment]
Should be possible now with ticket type statuses in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3) where it can be marked as disabled, but you'll still be able to pick a disabled ticket in the control panel, just not on the front-end.
