### ISSUE TITLE
Attach ticket(s) to E-Mail

### ISSUE THREAD

**Issue by mihob** [verbb/Events#127]
### Question

Is it somehow possible to send the purchased tickets as a PDF attachment by e-mail? For example, in addition to the invoice PDF in an order confirmation e-mail.

**Comment by engram-design** [comment]
Not currently, but similar to how [Gift Voucher](https://github.com/verbb/gift-voucher) handles this, it's possible to implement in the future.

**Comment by mihob** [comment]
Thanks for the feedback.

We have implemented it ourselves by customising the sending of the order confirmation via EVENT_BEFORE_SEND_MAIL and adding the tickets as an attachment.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
