### ISSUE TITLE
Translatable ticket fields do not work correctly

### ISSUE THREAD

**Issue by mihob** [verbb/Events#128]
### Describe the bug

We have a few translatable fields for our ticket types, where, for example, a short description is stored. 

It looks as if the correct translation is not loaded in the control panel, but only that of the default page. However, it is saved correctly.

The language switcher of the event index and the event detail does not seem to work properly either. The resulting URL does not look correct 

### Steps to reproduce

1. Select a language other than that of the default page
2. Change the ticket fields accordingly
3. Reload the event

### Craft CMS version

Craft Pro 4.5.11.1

### Plugin version

2.0.2

### Multi-site?

Yes

**Comment by mihob** [comment]
@engram-design Any news on this issue?

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/events:"dev-craft-4 as 2.0.2"`.

**Comment by engram-design** [comment]
Should be fixed in [2.0.3](https://github.com/verbb/events/releases/tag/2.0.3)
