### ISSUE TITLE
Insufficient validation of the ticket PDF download parameters

### ISSUE THREAD

**Issue by mihob** [verbb/Events#131]
### Describe the bug

The PDF download route has virtually no validation of the parameters. If none are specified, a 500 error occurs.

The ticketId parameter does not work at all.

It should be checked that all necessary parameters are present and valid before proceeding with processing

### Steps to reproduce

1. Visit https://example.com/index.php?p=actions/events/downloads/pdf without any parameters

### Craft CMS version

Craft Pro 4.5.13

### Plugin version

2.0.2

### Multi-site?

Yes

**Comment by engram-design** [comment]
The only real required parameter here is `number` for the order. As for the `ticketId` parameter - what about it doesn't work? That should return a single purchased ticket, as opposed to all purchased tickets for an order.

**Comment by mihob** [comment]
Sorry for the late reply

Yes that's right, I had only tested it without the order number.

It would definitely be good if at least the order number could be validated somehow.

That the controller simply crashes is not nice

**Comment by engram-design** [comment]
So that should be fixed in [2.0.3](https://github.com/verbb/events/releases/tag/2.0.3)
