### ISSUE TITLE
Ticket only available to purchase if enabled on primary site

### ISSUE THREAD

**Issue by samuelbirch** [verbb/Events#132]
### Describe the bug

I have a multi site setup, the default site has the ticket disabled but its enabled on the other 2 sites. The order orderSite is set to one of the other two sites (not the primary) so therefore i would expect the tickets to be available for purchase. I can add them to the cart on the frontend, but as soon as the cart is updated/saved it removes them. Via the cp i can't add them as it says they are not available.

### Steps to reproduce

1. multi-site setup
2. disable ticket for primary site
3. new order and set orderSite to the non primary site
4. try to add a ticket

### Craft CMS version

Craft Pro 4.5.14

### Plugin version

2.0.2

### Multi-site?

Yes

**Comment by engram-design** [comment]
I can't seem to replicate this immediately - can you let me know how you set `orderSite` on the order, in case that's something I'm doing differently? Everything seems to be working for me on a non-primary site setup.

**Comment by engram-design** [comment]
Closing due to age.
