### ISSUE TITLE
duplicate event but not tickets

### ISSUE THREAD

**Issue by CaporalJuju** [verbb/Events#133]
### Describe the bug

when I duplicate an event, the tickets are not duplicated

### Steps to reproduce

1. create an event with différent tickets price
2. duplicate the event

### Craft CMS version

4.5.5

### Plugin version

2.0.2

### Multi-site?

yes

**Comment by engram-design** [comment]
Should be fixed in [2.0.3](https://github.com/verbb/events/releases/tag/2.0.3)

**Comment by CaporalJuju** [comment]
Thanks, it s available in a dev craft branch ?
