### ISSUE TITLE
Separate user permission for event ticket settings

### ISSUE THREAD

**Issue by mihob** [verbb/Events#136]
### What are you trying to do?

Would it be possible to create a separate user permission for the event ticket settings? 

Our editors should also maintain the content of an event, but should not be able to mess around with the tickets (availability, prices, etc.)

### What's your proposed solution?

Add a separate user permission for event ticket settings

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3) with a whole new set of permissions for things.
