### ISSUE TITLE
Propagation Methods for events on multisite setups

### ISSUE THREAD

**Issue by mikeymeister** [verbb/Events#137]
### What are you trying to do?

It would be great if the user could choose which sites should have which events when the events are not relevant to every site.

### What's your proposed solution?

It would be amazing if it could behave the same way as the propagation options dropdown in the settings for entry sections. I couldn't say how that would work in practice though?

**Comment by engram-design** [comment]
Not a bad idea, I'll add this to our todo list.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
