### ISSUE TITLE
Multisite edit issues

### ISSUE THREAD

**Issue by samuelbirch** [verbb/Events#138]
### Describe the bug

Multisite setup, when viewing the events in a non primary site and then going in to edit one, it switches to the primary site, also once saving an event on a non primary site it takes you back to the element index but set to the primary site not the one you had just been editing.

### Steps to reproduce

1. view events on non primary site
2. edit an event
3. Is the site set to the correct one?
4. change to correct site if needed
5. save event
6. is the element index show the correct non primary site or has it switched back to the primary one.

### Craft CMS version

Craft Pro 4.6.1

### Plugin version

2.0.2

### Multi-site?

Yes

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/events:"dev-craft-4 as 2.0.3"`.

**Comment by engram-design** [comment]
Fixed in [2.0.4](https://github.com/verbb/events/releases/tag/2.0.4)
