### ISSUE TITLE
FR: Commerce Based Searches

### ISSUE THREAD

**Issue by JustJarethB** [verbb/Events#14]
A few queries I wish existed:
- `craft.events.purchasedTickets({ purchasedBy: cart.customer })`
All PurchasedTickets customer has bought
- `craft.events.tickets({ purchasedBy: cart.customer })`
All Tickets customer has purchased
- `craft.events.events({ purchasedBy: cart.customer })`
All Events customer has booked a ticket from
- `craft.events.hasTicket(order)`
Similar to `.isTicket` but can be run against orders. May be nice to integrate to `craft.orders({ hasTicket.. })` if possible

**Comment by JustJarethB** [comment]
Also these?
- `customer.hasPurchasedTicket(ticket)`
bool if customer has purchased ticket
- `customer.purchasedTicket(ticket)`
purchasedTicket or null, see above
- `customer.hasPurchasedEvent(event)`
bool if customer has purchased a ticket on provided event
- `customer.purchasedEvent(event)`
ticket or null, see above. Allows to chain from event to purchasedTicket

**Comment by engram-design** [comment]
Implemented most of these in [1.2.1](https://github.com/verbb/events/releases/tag/1.2.1):

`craft.events.purchasedTickets({ customer: cart.customer })`
All PurchasedTickets customer has bought.

`craft.events.tickets({ customer: cart.customer })`
All Tickets customer has purchased.

`craft.events.events({ customer: cart.customer })`
All Events customer has booked a ticket from.

`craft.events.hasTicket(order)`
Returns if there is at least one ticket in the provided order.

The following need not be included, as they can be achieved with the above element queries:
`customer.hasPurchasedTicket(ticket)`
`customer.purchasedTicket(ticket)`
`customer.hasPurchasedEvent(event)`
`customer.purchasedEvent(event)`

Thanks for the suggestions!
