### ISSUE TITLE
Events Causing Extra Shipping Charges in the Cart.

### ISSUE THREAD

**Issue by pbmills** [verbb/Events#140]
### Describe the bug

I've configured Seminars using the Events Plugin alongside Craft Commerce. In Commerce, my products include Books, each with two shipping options: Rural and Urban, each with different pricing tiers. For instance, for Rural shipping, if the book's cost is $1 - $100, the shipping cost is $7.80, and for anything $101 and above, it's $14.

Now, when a user adds a $55 book and a $150 seminar to their cart, the total comes to $205. However, at checkout, it seems that the Seminars product is unexpectedly adding a shipping cost. 

Despite my book being priced at $55 with an expected shipping cost of $7.80, the checkout is displaying a shipping cost of $14. This indicates that the system is calculating the total cart price instead of considering only the individual product at the commencement stage.

### Steps to reproduce

1. Adding Events tickets for me which is named as Seminars to cart
2. Adding product from the Craft Commerce to cart
3. checkout at Cart.

### Craft CMS version

4.6.0

### Plugin version

2.0.4

### Multi-site?

No

**Comment by engram-design** [comment]
Tickets aren't setup with dimensions or weight so they shouldn't be factored into shipping rules. In fact, we specifically say that [they're not shippable](https://github.com/verbb/events/blob/135bae8094f264026d2fc6268e7b4071b56c13be/src/elements/Ticket.php#L691).

What are you shipping rules and shipping setup? You may need to setup correct Shipping Categories (if you haven't already) so ensure that only the event types aren't factored into shipping calculations.

In your shipping rules, you might like to Disallow s shipping category you create. Then, hook that shipping category up to the ticket type.

<img width="757" alt="image" src="https://github.com/verbb/events/assets/1221575/68c1af9c-0ec1-4dbd-83a6-fdb1a93866c5">

**Comment by pbmills** [comment]
Hi,

I have created a shipping category for $0 and have applied that to events plugin but that isn’t getting applied to checkout for some reason. I have made sure of to Disallow of it to the ticket type but doesn’t seems to be working.




Regards,


Priti Burfield-Mills


M: 0220443081

W: https://burfieldmills.com

________________________________

**Comment by pbmills** [comment]
Hi,

This are the steps I am working on


 1) Created a Shipping Category with E-Tickets name


 2) Setting up Shipping Methods and Rules where I assigning disallow for the Shipping price.



3) Hooking that shipping category up to the ticket type



After doing all this when I go to front end, the shipping cost shows incorrect because it is calculating the total order value [Books as products and Seminars as E-Tickets] as Shipping. Where it should only be the Books.

Please help me, I have this website live and we having this issue on live site.

**Comment by engram-design** [comment]
Just to be clear, I meant that you should disallow the shipping category in your shipping method.

<img width="1469" alt="image" src="https://github.com/verbb/events/assets/1221575/f9be7432-b57b-4e48-bb39-7c909b8f9c6e">

So here I have a $10 flat rate shipping method, and I have set "Events" shipping category to "Disallow".

I then ensure my ticket types are using that same shipping category.

<img width="400" alt="image" src="https://github.com/verbb/events/assets/1221575/c121c448-9ce7-4667-9091-d30756963a77">

I'm not sure if your last response was supposed to contain attachments, but they haven't come through.

**Comment by pbmills** [comment]
Hi,

Yes, my last email should have attachment. I have just followed your setup and it isn’t working for me.

I have attached the screenshot. Hope if work this time?


Regards,


Priti Burfield-Mills


M: 0220443081

W: https://burfieldmills.com

________________________________

**Comment by pbmills** [comment]
Oh yes just checked that my last comment did missed the screenshots which they are here now with explanation.

 1) Created a Shipping Category with E-Tickets name
 
 
<img width="1554" alt="Screenshot 2024-02-02 at 22 13 30" src="https://github.com/verbb/events/assets/31907075/680dd617-ddda-40e6-940c-88ab222fdb85">



 2) Setting up Shipping Methods and Rules where I assigning disallow for the Shipping price.
![compass ploi-staging smokeylemon com_admin_commerce_shipping_shippingmethods_2_shippingrules_2](https://github.com/verbb/events/assets/31907075/c11d31d9-cda2-4e70-98a8-42a56cd53146)



3) Hooking that shipping category up to the ticket type

<img width="1561" alt="Screenshot 2024-02-02 at 22 15 09" src="https://github.com/verbb/events/assets/31907075/0b11ad6a-bb93-453e-bc5b-64daa5f43e3f">


The only change in my Shopping Conditions are the Total Value Order.

But yes, it is still not working for me. when I go to front end, the shipping cost shows incorrect because it is calculating the total order value [Books as products and Seminars as E-Tickets] as Shipping. Where it should only be the Books.

**Comment by engram-design** [comment]
Okay, I can see you've set up everything correctly, and I've replicated that on my end. It's indeed not working. Unfortunately, it looks like this might be a Commerce issue, where it's not taking into account the "Shipping Category Conditions" **before** actioning the "Order Total Value" value.

As you mentioned, the cart total is $205, but we want to remove the $150 item that's covered by the "E-Tickets" shipping category, with a "Disallow" condition on the shipping method.

We might have to raise this with the Commerce team. It's really down to how the [order total](https://github.com/craftcms/commerce/blob/ebed11720312d92309559e82d46748d2d0a90739/src/models/ShippingRule.php#L343) is calculated and there's not much we can do about it.

**Comment by pbmills** [comment]
@engram-design I have been in touch initially and they said to be in touch with the Events Plugin support. Is there any chance you can be in touch with them and raise the ticket about this issue? Or do I need to do that?

**Comment by engram-design** [comment]
@pbmills Was that through their support system (email), Discord or GitHub? If email, please cc me into the conversation with them! I'll reach out to them regardless about it

**Comment by pbmills** [comment]
It was via support. I will CC you shortly.

**Comment by pbmills** [comment]
@engram-design is this the right email address [web@verbb.io](mailto:web@verbb.io)?

**Comment by engram-design** [comment]
yup!

**Comment by john-henry** [comment]
I'm running into the same issue for Events v2 and Craft 4. Was there any resolution to this?

**Comment by engram-design** [comment]
@john-henry Looking back at our correspondence, looks like the Craft support crew replied with the following:

```
Nathaniel has given me a Twig condition that you should be able to use to calculate shipping without taking into account Events products. You would need to setup a Shipping Method with two shipping rules: one for under $100 and one for over $100.

On the <$100 rule, set the Order Condition Formula to:

order.lineItems|filter(lineItem => not lineItem.snapshot.event is defined)|map(lineItem => lineItem.subtotal)|reduce((carry, subtotal) => carry + subtotal) < 100
On the >$100 rule, set the Order Condition Formula to:

order.lineItems|filter(lineItem => not lineItem.snapshot.event is defined)|map(lineItem => lineItem.subtotal)|reduce((carry, subtotal) => carry + subtotal) > 100
And then set your shipping costs as required.

This works because it looks like Josh's plugin adds an event key to the line item snapshot. The condition will loop over line items and if that key is not present, it will add the subtotal to the amount to check against. Then, if the total is < or > 100, it will apply the rule.
```

**Comment by john-henry** [comment]
@engram-design Excellent, thanks. Ill give that a go
