### ISSUE TITLE
Cannot manually add ticket to order in CP

### ISSUE THREAD

**Issue by CharlieGentle** [verbb/Events#141]
### Describe the bug

When trying to create a new order in the CP, I cannot add any tickets for any events in the **Add a line item** section. Events are shown in the list but I cannot add any to an order.

### Steps to reproduce

1. Go to Commerce -> Orders -> New Order
2. Try to add an event ticket in the **Add a line item** section

### Craft CMS version

4.6.1

### Plugin version

dev-craft-4

### Multi-site?

Yes

**Comment by engram-design** [comment]
Is there no "Add" button, or it just won't work? A quick video on my end for a "seminar" ticket. https://share.cleanshot.com/74rWxNcD

**Comment by CharlieGentle** [comment]
The available tick is not showing and the checkbox is disabled for us.

**Comment by engram-design** [comment]
Strange. Any sort of permissions setup for the user?

**Comment by CharlieGentle** [comment]
No, I'm using an admin user

**Comment by engram-design** [comment]
Sorry for my lack of response to this. Happy to pick this up again if it's still an issue.
