### ISSUE TITLE
Ticket line items in cart not merged with cart when user logs in

### ISSUE THREAD

**Issue by CharlieGentle** [verbb/Events#142]
### Describe the bug

If I add a ticket to my cart as a guest user, when I then log in, my cart is empty.

When doing the same with just a normal Commerce product in the cart, the line item carries over to the logged in user's cart.

When logging in with a ticket and a normal Commerce product in the cart, my cart becomes empty.

### Steps to reproduce

1. Add a ticket to your cart as a guest user
2. Log in as an existing user
3. Check cart on front-end

### Craft CMS version

4.6.1

### Plugin version

dev-craft-4

### Multi-site?

Yes

**Comment by engram-design** [comment]
Looks like you're right, although the cart combining is all handled by Commerce (specifically [this](https://github.com/craftcms/commerce/blob/c730d0531c6db1722edaa76d7900c9d54a0641c9/src/services/Carts.php#L313)). We have no login handling on our end that might override anything Commerce-wise.

While I was able to replicate this once, after subsequent testing, it looks like line items are actually copying over now, so this issue may be sporadic - somehow. I was also combining checking the cart content from the control panel.

**Comment by CharlieGentle** [comment]
This is happening consistently for us and haven't managed to get a ticket line item to copy over. The presence of a ticket line item also stops other line items from copying over.

**Comment by engram-design** [comment]
Still trying to figure out what's going on here, stay tuned.

**Comment by engram-design** [comment]
I believe this should be fixed in Commerce 5 and Events 3.
