### ISSUE TITLE
Disable deleting a ticket if it's it's already been purchsed

### ISSUE THREAD

**Issue by anchovy** [verbb/Events#143]
### What are you trying to do?

If 1 or more tickets for an event have been purchased then disable deleting of the ticket in the CP.

### What's your proposed solution?

One idea would be to set the quantity for the ticket to '0' if the ticket has already been purchased and the 'x' is clicked, maybe add a message 'This ticket can't be deleted as it has been purchased already - The quantity has been set to zero so it can't be purchased again.'

OR just throw up an alert: 'This ticket can't be deleted as it has been purchased already - if you don't want it to be purchased again set the quantity to 0.

etc.

**Comment by engram-design** [comment]
Yeah, probably not a bad idea to add something like this. They'll still need the ability to change stock, just probably not deletion enabled.

**Comment by anchovy** [comment]
Totally - should still be able to set quantity to 0, but jut not delete.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.4](https://github.com/verbb/events/releases/tag/3.0.0-beta.4)
