### ISSUE TITLE
Total capacity always defaults to 0 making it always required or the event becomes unavailable

### ISSUE THREAD

**Issue by WebitMaxime** [verbb/Events#144]
### Describe the bug

Hello,

**Expected behaviour:**
- Total capacity shouldn't be required, but an option that can be paired with "per ticket" quantity
- Allow an empty (not zero) total capacity field where we can control the quantity "per ticket" rather than having to do the math for all tickets which becomes horrible when we have events with over 20 ticket types and specific quantities per ticket

**Actual behaviour:**
- Total capacity reverts to 0 therefore making the event unavailable even if there are quantities per tickets
- Have to sum all ticket quantities in order to have all parameters respected (or set to an absurd high amount like 99999 even though I am unsure if that would even work if/when all ticket quantities are gone while verifying the event.isAvailable property)

### Steps to reproduce

1. Remove total capacity (defaults to 0)
2. Set quantity per ticket
3. Verify if the event is available via event.isAvailable property

### Craft CMS version

4.7.3

### Plugin version

2.0.4

### Multi-site?

Yes

### Additional context

Version 2.0.4 has made it so we can set ticket quantity to a null field, but this is expected for the total capacity as well, so we can have an "either or" logic rather than being forced into unintended values and behaviors.

**Comment by anchovy** [comment]
I second this - we've had the same issue before. Total capacity isn't needed in my opinion at all, either tickets have a quantity which needs to be respected or like a commerce product set the quantity to unlimited.

**Comment by engram-design** [comment]
Agreed that this needs to be refactored and better managed, I wasn't overly happy with this even at the time. 

We're also probably going to do away with how the quantities' respective values get modified when tickets are purchased. It leads to confusion on what the original allocated quantity was, and how many have been purchased. You you might enter `30` with 5 tickets being purchased, and the value gets set to `25`. While this is useful it become ambiguous on how many you actually started with.

**Comment by engram-design** [comment]
> Total capacity isn't needed in my opinion at all

That's not entirely true, and some people want to over-allocate tickets per type, but not go over the venue's capacity.

Say your event can only handle 100 people. You also have Adult, Child and Concession tickets available. You essentially want "unlimited" tickets for each type, but can't sell over the 100 total tickets. You would set each ticket's capacity to 100. But without the event-level capacity, that means you could potentially have 300 tickets sold to an event. And you certainly wouldn't want to start splitting the capacity between tickets like 50 Adult, 25 Child, 25 Concession, that's just not (typically) fair.

**Comment by anchovy** [comment]
That's a fair point. 

There are a few scenarios here though. In our case, we've got some tickets that need an unlimited quantity i.e. webinar access to the recording, but we might want to limit other tickets to the 'live' event.

So we'd have a total tickets = 100 for tickets a-b but unlimited for ticket c.
So - can we have:
1: total tickets, number or unlimited.
2: Individual - number or unlimited.
![image](https://github.com/verbb/events/assets/599005/5012d44c-0f4a-4689-bb9a-9043908c2d5c)
2.a: if 1 is a number, then a further option on the individual tickets to allow exceeding total ticket.
Or... 
2.b: in our case, a flag or a setting on the ticket that allows it to ignore the total capacity - so it appies accross all events where it's used.

Just my 2 cents worth.

**Comment by engram-design** [comment]
Updated in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3)
