### ISSUE TITLE
Feature Request: Support Start Date / End Date in Craft 5's card view mode

### ISSUE THREAD

**Issue by RitterKnightCreative** [verbb/Events#149]
### What are you trying to do?

One the new features of Craft 5 is card view and the ability to pick which fields you want to see in card mode. 

I know Events is currently in beta for Craft 5 and you're probably already aware of this... but it would be useful to be able to see the Start Date / End Dates of the event in Craft 5's card view mode.

### What's your proposed solution?

Ability to See Start Date / End Date in Craft 5's card view mode.

### Additional context

As a workaround, something like Preparse might work in the interim.

**Comment by engram-design** [comment]
Great to add this to my radar on upcoming v3 stuff, certainly will add support for that, if possible given how events will support multiple start/end dates now.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3)
