### ISSUE TITLE
Deleting Ticket Type Breaks Events That Were Assigned It

### ISSUE THREAD

**Issue by CC-DP** [verbb/Events#15]
### Description
Admin panel edit event pages break when an associated ticket type is deleting before removing it from the event.

### Steps to reproduce

1. Create event and ticket types.
2. Assign ticket to event.
3. Delete ticket type and try to edit event again.

Returns error:
    Invalid Configuration – yii\base\InvalidConfigException
    Invalid ticket type ID: 2976

### Additional info

- Plugin version: 1.1.1
- Craft version: Solo 3.2.2

**Comment by engram-design** [comment]
Should be fixed in [1.1.2](https://github.com/verbb/events/releases/tag/1.1.2)
