### ISSUE TITLE
Purchased Tickets Filter Not Working

### ISSUE THREAD

**Issue by pixelandbrick** [verbb/Events#151]
### Describe the bug

The "Purchased tickets" tab does not yield any results when filtering: "Related to" "Event" and a particular event. I can see in the "All purchased tickets" view (with no filters applied) that I do indeed have tickets purchased for the given event.

### Steps to reproduce

1. Purchase a ticket for an event
2. Confirm the purchase shows up in "All purchased tickets" view of Purchased tickets tab
3. Filter by "Related to" "Event" and select the ticket's event

### Craft CMS version

5.2.8 pro

### Plugin version

3.0.0-beta2

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3), note that there's now an "Event" condition which should be used, rather than Related To.
