### ISSUE TITLE
Discounts/Coupons not working with event tickets (3.0.0-beta.2) 

### ISSUE THREAD

**Issue by CAIDcreative** [verbb/Events#152]
### Describe the bug

I cannot get discounts/coupons to work with event tickets. There doesn't seem to be an option to set a ticket as 'promotable' and even when I have gone into the commerce_purchasables_stores table and set a ticket to be 'promotable' value from a 0 to 1 and run craft commerce/pricing-catalog/generate in the terminal to generate the catalogue of prices I still cannot get a coupon to discount event ticket prices.

### Steps to reproduce

1. Create an event and ticket
2. Create a discount with a coupon code, and set a Ticket to be a Matching Item
3. Add a ticket and coupon code to an order

### Craft CMS version

Craft Pro 5.3.2

### Plugin version

3.0.0-beta.2

### Multi-site?

No

### Additional context

A bit new to commerce 5 so having to understand how discounts work, and not sure if this is a commerce or events issue. I have been able to get discounts working for products and varients in commerce but I can't get it working for event tickets.

**Comment by CAIDcreative** [comment]
So I think I've solved it for my use case by adding 
`public bool $promotable = true;`
To line 43 of /vendor/verbb/events/src/elements/Ticket.php alongside the other constants. All tickets are promotable in my case but I would recommend adding an lightswitch on the frontend for tickets to be able to select whether their promotable or not.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
