### ISSUE TITLE
Conflict with seomatic 5.1.6

### ISSUE THREAD

**Issue by cloudgrayau** [verbb/Events#157]
### Describe the bug

PHP Compile Error – [yii\base\ErrorException](https://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Declaration of verbb\events\integrations\seomatic\Event::previewUri(string $sourceHandle, $siteId) must be compatible with nystudio107\seomatic\base\SeoElementInterface::previewUri(string $sourceHandle, $siteId, $typeId = null): ?string

### Steps to reproduce

After upgrade to the latest versions of seomatic and events.

### Craft CMS version

5.5.0

### Plugin version

3.0.1

### Multi-site?

Yes

**Comment by cloudgrayau** [comment]
It appears the last update of seomatic has changed that function. I have reverted seomatic back to 5.1.5 for now.

@khalwat

**Comment by engram-design** [comment]
Yep, their plugin changed the method signatures (a breaking change, I’ve already told Andrew off haha), but will get a patch to address it on my end.

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/events/releases/tag/3.0.2)

**Comment by khalwat** [comment]
Sorry guys, this is my bad. I didn't realize anyone outside of custom module users were using this interface.
