### ISSUE TITLE
Cant change "Purchased Tickets" field settings at event fields

### ISSUE THREAD

**Issue by mihob** [verbb/Events#159]
### Describe the bug

It is not possible to access the settings of the "Purchased Tickets" field in the CP under "Event Fields" of an event type

The following error occours:
<img width="344" alt="grafik" src="https://github.com/user-attachments/assets/cf8a13a8-b94e-42d3-b03f-01bd87b51c4f">

### Steps to reproduce

1. Try to access settings of the "Purchased Tickets" field in the CP under "Event Fields"

### Craft CMS version

5.5.0.1

### Plugin version

3.0.1

### Multi-site?

YES

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/events:"dev-craft-5 as 3.0.2"`.

**Comment by engram-design** [comment]
Fixed in [3.0.3](https://github.com/verbb/events/releases/tag/3.0.3)
