### ISSUE TITLE
Are You Sure on Delete Ticket

### ISSUE THREAD

**Issue by CC-DP** [verbb/Events#16]
### Description
When editing many events and tickets quickly, the first gear icon click on a ticket shifts the tickets pane slightly so opening all of the tickets quickly leads to accidentally deleting some without checking if deleting was intended, resulting in having to reload the screen to get the ticket back.

### Steps to reproduce

1. Create/edit event and go to tickets pane.
2. When clicking gear icons quickly on tickets to open them all up, tickets pane shifts slightly and clicking next icon usually results in clicking delete button.

### Additional info

- Plugin version: 1.1.1
- Craft version: Solo 3.2.7

**Comment by engram-design** [comment]
Added in [1.1.7](https://github.com/verbb/events/releases/tag/1.1.7)
