### ISSUE TITLE
Link to Emails under Settings>Emails wrong

### ISSUE THREAD

**Issue by mihob** [verbb/Events#160]
### Describe the bug

The link to an email under Settings>Emails seems to be wrong and leads to a 404 page.

Wrong:
`https://example.test/commerce/settings/emails/1?site=german`

Correct:
`https://example.test/commerce/settings/emails/primaryStore/1?site=german`

### Steps to reproduce

1. Try to access an email under Settings>Emails

### Craft CMS version

5.5.0.1

### Plugin version

3.0.1

### Multi-site?

YES

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/events:"dev-craft-5 as 3.0.2"`.

**Comment by engram-design** [comment]
Fixed in [3.0.3](https://github.com/verbb/events/releases/tag/3.0.3)
