### ISSUE TITLE
Title of Events>Purchased Tickets is not translatable

### ISSUE THREAD

**Issue by mihob** [verbb/Events#162]
### Describe the bug

The title of the Purchased Tickets section under Events>Purchased Tickets is not translatable.

<img width="1478" alt="grafik" src="https://github.com/user-attachments/assets/433b658e-43ca-47cf-8273-aacb6a937cbb">

### Steps to reproduce

1. 
2. 

### Craft CMS version

5.5.0.1

### Plugin version

3.0.1

### Multi-site?

YES

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/events:"dev-craft-5 as 3.0.2"`.

**Comment by mihob** [comment]
Thanks for the quick fix. I found a few other places with untranslatable strings.

<img width="1350" alt="grafik" src="https://github.com/user-attachments/assets/d6dd949d-3109-4786-822f-5c5c148c7afc">

<img width="1045" alt="grafik" src="https://github.com/user-attachments/assets/7996cb0d-a1af-4c7f-84f3-ace0593ee299">

**Comment by engram-design** [comment]
Sorry about that, looks like I'd actually missed a few different translation strings. Fixed for the next release. To get this early, run `composer require verbb/events:"dev-craft-5 as 3.0.2"`.

**Comment by engram-design** [comment]
Fixed in [3.0.3](https://github.com/verbb/events/releases/tag/3.0.3)
