### ISSUE TITLE
Tickets with deactivated type are displayed incorrectly

### ISSUE THREAD

**Issue by mihob** [verbb/Events#164]
### Describe the bug

Tickets with deactivated type are displayed incorrectly

Before deactivating the type:
<img width="1054" alt="grafik" src="https://github.com/user-attachments/assets/e5fbd047-9854-4e71-9124-4d14472e5baa">

After deactivating the type:
<img width="1025" alt="grafik" src="https://github.com/user-attachments/assets/f205a85c-afca-4c29-9c6e-8398b8a28095">

### Steps to reproduce

1. 
2. 

### Craft CMS version

5.5.0.1

### Plugin version

3.0.1

### Multi-site?

YES

**Comment by engram-design** [comment]
That's a tricky one, because the title is derived dynamically from the type (at least by default). If it's removed, then it can't be used to generate the title.

Otherwise, we have to statically generate the title every time the ticket or ticket type changes, which is obviously a performance hit when dealing with these elements.

I suppose in this case the ticket type isn't _gone_, so we could retain that reference. Although that might be tricky in practice _just_ for the title. We wouldn't want to have a ticket's type return a disabled ticket type otherwise.

**Comment by mihob** [comment]
But the type is only deactivated. Within the control panel, the deactivated type entry should still be delivered for queries.

**Comment by engram-design** [comment]
Yep, considering the best way to make this work, as under the hood we're just rendering a Twig string with a Ticket element:

```twig
{type.title} - {session.title}
```

`type` in this instance resolves to `Ticket::getType()` which will only return enabled Ticket Types, which is what we'd want for any normal use of this, particularly for the front-end. As I've mentioned, we'd want to make this specific to this string.

**Comment by mihob** [comment]
This also means that deactivated ticket types cannot really be used in orders, as the editor no longer really knows what it has added. (see https://github.com/verbb/events/issues/126) 

Wouldn't it be a solution to make an exception for cp requests in Ticket:getType()?

**Comment by engram-design** [comment]
You don't interact with Ticket Types in orders anyway. You add Ticket elements to your orders, and its arguable if you should be able to pick a Ticket that has a disabled Ticket Type anyway. If any part of a Ticket is disabled, whether that be the Event, Session or Ticket Type, it shouldn't be purchasable.

Yes, that's where I'm heading at the moment, but just testing all the different scenarios for it.

**Comment by mihob** [comment]
Yeah well, i mean tickets with deactived types. My usecase was described in the other ticket https://github.com/verbb/events/issues/126. 

And I still think that an admin/editor should be able to use tickets that a frontend user does not have access to.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/events:"dev-craft-5 as 3.0.3"`.

**Comment by engram-design** [comment]
Fixed in [3.0.4](https://github.com/verbb/events/releases/tag/3.0.4)
