### ISSUE TITLE
Changing the layout of the ticket types table of an event has no effect on the table itself

### ISSUE THREAD

**Issue by mihob** [verbb/Events#167]
### Describe the bug

Changing the layout of the ticket types table of an event has no effect on the table itself

<img width="1054" alt="grafik" src="https://github.com/user-attachments/assets/e80508b5-35f3-40f4-80c5-5a2ed10c0b70">

<img width="1046" alt="grafik" src="https://github.com/user-attachments/assets/bc19301c-7f05-4c76-a9d6-7d36dffeb578">

### Steps to reproduce

1. Change the displayed columns of the Ticket Types table under View

### Craft CMS version

5.5.2

### Plugin version

3.0.3

### Multi-site?

YES

**Comment by engram-design** [comment]
In my testing, this only seems to be an issue with custom fields. Just wanted to check if that was the same on your end, as you've redacted those other columns?

**Comment by mihob** [comment]
Yes sorry, this only affects columns for custom fields

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/events:"dev-craft-5 as 3.0.3"`.

**Comment by engram-design** [comment]
Fixed in [3.0.4](https://github.com/verbb/events/releases/tag/3.0.4)
