### ISSUE TITLE
Packagist/Craft Plugin Store Stuck at 1.1.1

### ISSUE THREAD

**Issue by jacobgraf** [verbb/Events#17]
It looks like Packagist, and in turn the Craft Plugin Store, are now properly refreshing to 1.1.1. Can you fix this so we can pull down 1.1.2? Thanks!

**Comment by engram-design** [comment]
Weird, looks like the hook failed, but also just pushed [1.1.3](https://github.com/verbb/events/releases/tag/1.1.3) which is also on Packagist!
