### ISSUE TITLE
FR: nesting events

### ISSUE THREAD

**Issue by KatieMFritz** [verbb/Events#18]
### Description
We're setting up conferences that have many sessions. One conference can have many sessions, and each session belongs to exactly one conference. Sessions and conferences are separate event types.

I was originally trying to link sessions and conferences with reciprocal fields, which is why I posted https://github.com/verbb/events/issues/13. 

However, a parent-child relationship would also work and might be easier! Would it be feasible to allow nesting of events, even across event types, like you would for a structure that has different entry types? Are there negative consequences I'm not seeing?

**Comment by engram-design** [comment]
For this reason, we're proposing "Event Sessions" - https://github.com/verbb/events/issues/81.

I think nested events might be annoying to manage in practice, specifically doubling up content.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3). It's not specifically nested events, but it's the ability to define multiple sessions in one event. I believe that should suffice!
