### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by mikestecker** [verbb/Events#2]
Saw this when installing:
`Package endroid/qrcode is abandoned, you should avoid using it. Use endroid/qr-code instead.`

**Comment by mikestecker** [comment]
Also, might want to ensure Commerce is installed... I was adding to a test site locally that didn't have Commerce installed and was greeted with all sorts of fun errors.

**Comment by engram-design** [comment]
Thanks on both counts, didn't realise there was a warning about `endroid/qrcode`. I have updated it, but still a few versions behind due to PHP 7 compatibilities. Works great though.

Fixed in [1.0.1](https://github.com/verbb/events/releases/tag/1.0.1)
