### ISSUE TITLE
Can no longer query past events

### ISSUE THREAD

**Issue by satcreative** [verbb/Events#22]
### Description
I had a component on my site that displayed past events using the below code:

{% set pastEvents = craft.events.events()
    .startDate("< #{start}")
    .all() %}
{% for pastEvent in pastEvents %}
    {{ pastEvent.title }}
{% endfor %}

This was working fine, however it has now stopped working. I've only noticed today, but wonder if it was a result of the plugin updates on 8th and 9th Aug.

Can anyone else get this query to output past events?

### Additional info

- Plugin version: 1.1.5
- Craft version: Craft Pro 3.2.9

**Comment by engram-design** [comment]
So this behaviour was changed in [1.1.0](https://github.com/verbb/events/releases/tag/1.1.0), to by default, only showing events that are currently on.

You'll want to have a look at https://verbb.io/craft-plugins/events/docs/template-guides/events-index#past-events

Sorry if this wasn't clear in the release notes.
