### ISSUE TITLE
Family Tickets

### ISSUE THREAD

**Issue by samuelbirch** [verbb/Events#25]
Can we have the feature to be able to assign a "seat" quantity to a ticket type please?

This would allow the ability to have family or group tickets that would count against the total capacity. 

eg: total capacity is 100, a single family ticket (4 persons) is purchased and the total capacity left if now 96, even though 1 ticket have been bought.

**Comment by engram-design** [comment]
Great thinking here for sure. Adding to the 2.0.0 milestone.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.4](https://github.com/verbb/events/releases/tag/3.0.0-beta.4)
