### ISSUE TITLE
Bug: Reached maximum ticket quantity for event

### ISSUE THREAD

**Issue by samuelbirch** [verbb/Events#27]
I've got the total capacity set but not the quantity on the ticket, and when i try to add to my basket I get the "You reached the maximum ticket quantity for the event" message.

The same happens if no total capacity and no ticket capacity is set. It only works if a ticket capacity is set.

**Comment by engram-design** [comment]
I've fixed this in [1.1.7](https://github.com/verbb/events/releases/tag/1.1.7)
