### ISSUE TITLE
Missing manageTicketTypes permission

### ISSUE THREAD

**Issue by andygrn** [verbb/Events#30]
### Description

TicketTypesController requires the `events-manageTicketTypes` permission, but this permission is not registered by the plugin. Non-admins trying to add or edit ticket types get a 403 forbidden response.

https://github.com/verbb/events/blob/craft-3/src/controllers/TicketTypesController.php#L22
https://github.com/verbb/events/blob/craft-3/src/Events.php#L195

### Steps to reproduce

1. Log in as any non-admin user with all available Events plugin permissions granted.
2. Try to add or edit a ticket type.

### Additional info

- Plugin version: 1.1.6
- Craft version: 3.2.10

**Comment by engram-design** [comment]
Fixed in [1.1.7](https://github.com/verbb/events/releases/tag/1.1.7)
