### ISSUE TITLE
Check-in didn't work until I uncommented this line in the TicketController actionCheckin method 

### ISSUE THREAD

**Issue by stuh** [verbb/Events#31]
https://github.com/verbb/events/blob/23ca9035f3edf8f7fd700da3382352ce559f0253/src/controllers/TicketController.php#L52

Hi, great plugin so far. Not sure if this is intentional or not but I noticed when I checked-in tickets it didn't actually update the DB. Found this commented out line which was the culprit.

**Comment by engram-design** [comment]
Fixed in [1.1.7](https://github.com/verbb/events/releases/tag/1.1.7)
