### ISSUE TITLE
Check in broken on v1.1.6

### ISSUE THREAD

**Issue by russback** [verbb/Events#33]
### Description

Line 52 of TicketController has the `Events::$plugin->getPurchasedTickets()->checkInPurchasedTicket($purchasedTicket);` call commented out so the function returns a success message but checkin is not recorded.

### Steps to reproduce

1. Post to `events/ticket/checkin` with a `PurchasedTicket` sku.
2. Inspect the `events_puchasedTickets` table to verify that `checkedIn` is `null` and `checkedInDate` is `null`

### Additional info

- Plugin version: 1.1.6
- Craft version: 3.3.11

**Comment by engram-design** [comment]
Fixed in [1.1.7](https://github.com/verbb/events/releases/tag/1.1.7)
