### ISSUE TITLE
Tickets are not shippable and are forced to have free shipping but use shipping categories

### ISSUE THREAD

**Issue by lukeholder** [verbb/Events#37]
### Description

Ticket Purchasables are marked as having free shipping as well as non-shippable:

See code here: 
https://github.com/verbb/events/blob/craft-3/src/elements/Ticket.php#L617-L630

This means that shipping cost rules can not be applied to them, even though there is support for shipping categories for ticket types. You may want to document that shipping costs can not be added to tickets.

**Comment by engram-design** [comment]
Thanks for the heads-up here, I didn't realise the free shipping function would have that effect. Updated in [1.2.0](https://github.com/verbb/events/releases/tag/1.2.0)
