### ISSUE TITLE
User group preferences for Manage event type are not applied

### ISSUE THREAD

**Issue by timprint** [verbb/Events#38]
### Description
I have an "Administrators" user group. I would like them to be able to manage tickets for an event but not create new event types. The preference for the group are.

Manage event types - unchecked
Manage Events - checked
Manage my event - checked
Manage ticket types - unchecked

### Steps to reproduce

1. Log in as user in Administrators group.
2. Go to Events
3. Event Types is visible in the sidebar
4. "New event" type button is visible
5. Clicking "New event type" button gets HTTP403 forbidden 

The Event types option should not be available in the sidebar menu.

### Additional info

- Plugin version: 1.17.1
- Craft version: 3.3.18.2

**Comment by engram-design** [comment]
Fixed in [1.2.0](https://github.com/verbb/events/releases/tag/1.2.0)
