### ISSUE TITLE
Empty array from query

### ISSUE THREAD

**Issue by ardian-c** [verbb/Events#40]
### Description
I have integrated the plugin, create a number of events of different types, however when querying them I'm getting an empty array. 

### Steps to reproduce

1. Created a number of events, say 20. 
2. Queried using the following expression: ```{% set events = craft.events.events().all() %} ```
3. The result I get from ```{{ dump(events) }}``` is an empty array. Am I missing something? 
### Additional info

- Plugin version: 1.3.0
- Craft version: 3.4.0.2

**Comment by engram-design** [comment]
Do your events have end-dates set in the future? Reason I ask is that by default, only current events are shown - https://verbb.io/craft-plugins/events/docs/template-guides/available-variables#craft-events-events

**Comment by ardian-c** [comment]
No, I haven't specified any start or end dates.  I should be able to get all events with no specified dates, just to show them, i.e archive page? 

Thanks

**Comment by engram-design** [comment]
@ardian-c Can you try using `{% set events = craft.events.events({ endDate: null }).all() %}` just to test? This will fetch all events, including ones in the past.

**Comment by ardian-c** [comment]
Yes, that did work. Thank you.
