### ISSUE TITLE
[FR] Assign custom fields to purchased tickets element

### ISSUE THREAD

**Issue by sjcallender** [verbb/Events#42]
### Description
With the purchased tickets now stored as elements, it be incredible to be able to edit the custom fields mapped to them.

In our case, a person can purchase multiple tickets on behalf of others. We save the attendee info in the Order options. We are planning on adding our own db table to then store the attendee info outside of orders for easy querying. Even better would be able to add that attendee info to custom fields on a purchased ticket.

**Comment by engram-design** [comment]
Yep, that's the plan. Previously, you can store data on line item options (you still can, and always will), but we'll be evolving this to include the ticket (and maybe event) fields, so that you can still assign them to event/ticket types, but they're also applied to the purchased ticket.

Will be in the next minor release.

**Comment by sjcallender** [comment]
You're our favorite. 🤩

**Comment by sjcallender** [comment]
If you're feeling extra giving, adding in a CSV export for the purchased ticket table would be incredibly helpful.

**Comment by engram-design** [comment]
@sjcallender The current element export functionality doesn't work for you?

**Comment by sjcallender** [comment]
Oh, yeah that'll work. We can't upgrade to the newer version yet because of other dependencies, so I haven't been able to test.

**Comment by engram-design** [comment]
Exporting to CSV works in Craft 3.3/Commerce 2.x - but you'll get much more benefit when using on Craft 3.4, as there's a lot more control over what you can do, module manipulation, etc.

**Comment by jonXmack** [comment]
Is there an ETA on this @engram-design ? I'm in a similar position where each ticket needs to have attendee details mapped to it. I've currently got a matrix as an order field which is populated via the front end during the checkout process but that has some shortcomings, having it as a ticket field would be perfect.

**Comment by engram-design** [comment]
I can't guarantee an ETA, but we'd expect to be able to fit it in, in the next 1-2 months.

**Comment by engram-design** [comment]
Added in [1.4.0](https://github.com/verbb/events/releases/tag/1.4.0), just have a look at the tweaked [docs](https://verbb.io/craft-plugins/events/docs/template-guides/single-event) as well.

Special thanks to @samuelbirch for the PR.
