### ISSUE TITLE
Server Error when trying to access Events > Purchased Tickets

### ISSUE THREAD

**Issue by jacobgraf** [verbb/Events#43]
### Description
Server Error when trying to access **Events** > **Purchased Tickets**

When looking at web.log, I see this error...

`2020-02-01 13:03:37 [-][1][-][error][RuntimeException] TypeError: Argument 1 passed to verbb\events\services\Events::getEventById() must be of the type int, null given, called in /home/forge/mysite.com/vendor/verbb/events/src/elements/PurchasedTicket.php on line 215 and defined in /home/forge/mysite.com/vendor/verbb/events/src/services/Events.php:20`

### Additional info

- Plugin version: 1.3.1
- Craft version: Pro 3.4.2
- Commerce version: Lite 3.0.5

**Comment by engram-design** [comment]
Should be fixed in [1.3.2](https://github.com/verbb/events/releases/tag/1.3.2)
