### ISSUE TITLE
Love the New "Purchased Tickets" View, Add Ability to Bulk Update Order Status

### ISSUE THREAD

**Issue by jacobgraf** [verbb/Events#44]
Not sure if this is a technical limitation, but we use Order Status' to send emails, etc related to our events. I love the new "Purchased Tickets" view, but would love to be able to select all (per event) and bulk change the Commerce Order status for those orders.

Also, I'd love to be able to filter by event status (enabled, disabled, expired, etc).

Thanks for listening!

**Comment by engram-design** [comment]
Not sure I follow with this one, sorry! You're saying you want to toggle the order status or any purchased ticket, from the purchased ticket? My only real concern with that, is what if an order contains multiple tickets across multiple events? Or contains other purchasables? Would love to hear your use-case.

More filtering options are certainly on the cards.

**Comment by engram-design** [comment]
Filtering is now possible for purchased tickets in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3), but as for being able to set the Commerce order status from a purchased ticket, that's a bit more complicated, and might be something a module takes care of for your site.
