### ISSUE TITLE
[FR] Recurring Events

### ISSUE THREAD

**Issue by mikestecker** [verbb/Events#45]
Any chance of adding yet even more complexity to events and adding support for recurring events?

**Comment by engram-design** [comment]
Its in the long-term roadmap/wishlist, but there's no plans for it just yet.

**Comment by williamhibberd** [comment]
This feature would be really useful for an upcoming project.

**Comment by jacobgraf** [comment]
Yes, this would be very handy for us too.

**Comment by kevadamson** [comment]
Yes, definitely would like this. So, ability to add more than one start and end date, with each having their own ticket types.

**Comment by engram-design** [comment]
Scheduled for 2.0.0 (no ETA)

**Comment by janeschindler** [comment]
any updates on this @engram-design ?

**Comment by engram-design** [comment]
Not for a little while yet, sorry. We're prioritizing Craft 5 updates, and we'll circle back to this next year (as an estimate)

**Comment by janeschindler** [comment]
thanks for answering! actually also curious: hows that reservations plugin coming along? Wondering what it will do that events doesn't do / whether we should wait for it. Do you have any more infos or a roadmap on that @engram-design ? Referring to https://verbb.io/craft-plugins

**Comment by engram-design** [comment]
It's scheduled for roughly the same time. We're still in two minds about it being a separate plugin, or part of Events (or combining both into a new one). But it will definitely be more geared towards bookings and reservations, as opposed to ticketed events. No roadmap on that one, we're actively working on it.

**Comment by janeschindler** [comment]
thanks so much for hte info @engram-design . Awesome and very helpful.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
