### ISSUE TITLE
Feature Request - Import Events with Feed Me

### ISSUE THREAD

**Issue by peteeveleigh** [verbb/Events#46]
Would be really nice to be able to import Events using FeedMe - currently Events aren't available as an Element Type that FeedMe works with. 

Is that on the cards and if so, could it be added tomorrow? ;-)

**Comment by engram-design** [comment]
Not going to be added tomorrow, I can assure you 😎

We'll add it to our list.

**Comment by peteeveleigh** [comment]
@engram-design I've actually managed to make a few mods to FeedMe to import Events. 
Once I'm sure that's working as it should I'll submit a PR to FeedMe.

Should it be possible to add the functionality via the Events plugin though? Rather than modifying Feedme itself (added an Event Element and templates).

**Comment by engram-design** [comment]
Hard to say, I've honestly not looked at Feed Me since it was acquired by Pixel & Tonic, but we should be able to use the  existing element-registration hooks for Feed Me to register our custom element handling functionality via https://docs.craftcms.com/feed-me/v4/developers/element-types.html

**Comment by johnj24** [comment]
A Feed Me integration would be great. I'm looking at transferring a few hundred events from Solspace Calendar to Events.

**Comment by engram-design** [comment]
Added in [1.4.5](https://github.com/verbb/events/releases/tag/1.4.5), but note that importing tickets isn't supported at this time.
