### ISSUE TITLE
[FR] Manual CP checkin

### ISSUE THREAD

**Issue by samuelbirch** [verbb/Events#47]
Can we have the ability to manually checkin a ticket via the CP? - so we don't need to go to the checkin url.

Doing it via the purchased ticket detail page and via the listing view (so multiple tickets can be checked in) would be great.

Also, can we have the ability to undo a checkin?

**Comment by engram-design** [comment]
Thanks for the PR, and added in [1.4.0](https://github.com/verbb/events/releases/tag/1.4.0)
