### ISSUE TITLE
[FR] CP QRcode checkin

### ISSUE THREAD

**Issue by samuelbirch** [verbb/Events#48]
If you be really nice that if you are currently logged into the cp (or are a user that has cp access) and you scan a ticket QRcode, that the page redirect actually takes you to the purchased tickets index page for that event in the cp.

if not logged into the cp (or have access) then do the current functionality.

**Comment by engram-design** [comment]
Thanks for the PR, and added in [1.4.0](https://github.com/verbb/events/releases/tag/1.4.0)
