### ISSUE TITLE
500 error for events.js

### ISSUE THREAD

**Issue by KatieMFritz** [verbb/Events#5]
Only on my staging site (Fortrabbit + Forge), not my local site (valet). `events.js` also shows up twice in Network on the staging site, with the same URL. If I try to open it in a new tab, it says `fopen(/home/forge/dev.facadetectonics.org/web/cpresources/2d10db37/js/events.js): failed to open stream: No such file or directory`

<img src="https://d3dr1ze7164817.cloudfront.net/items/1z3T1Q0q2l1a0s053v2g/Image%202019-04-29%20at%208.52.32%20PM.png">

<img src="https://d3dr1ze7164817.cloudfront.net/items/3O462Y2E2s432R2I2l3w/Image%202019-04-29%20at%208.59.50%20PM.png">

**Comment by engram-design** [comment]
Should be fixed in https://github.com/verbb/events/releases/tag/1.0.2.1

**Comment by KatieMFritz** [comment]
Yes, that's working and now there is only one `events.js` in the Network tab. Thanks for the prompt fix! 🎉
