### ISSUE TITLE
Commerce version support

### ISSUE THREAD

**Issue by samuelbirch** [verbb/Events#52]
Hi Josh,

The 1.4 version is updated to work with craft 3.4 and commerce 3. 
My query is... is commerce 3 a requirement? - i've tested locally running it with commerce 2 and it seems to work fine. I was just wondering if there was something that made it commerce 3 only or would it be possible to set the requirement back to commerce 2?

Cheers

**Comment by engram-design** [comment]
Commerce 3 isn't strictly required for 1.4.x, but its enforced. We use the Vue admin table's, introduced in Craft 3.4.x.

Viewing the ticket type index and event type index will throw an error in Craft 3.3. I suppose you could run Commerce 2 on Craft 3.4, but I'm not sure on the implications of that. You'd have to ask the Commerce crew, but I'm requiring an update across the board.

**Comment by samuelbirch** [comment]
ok thats fair enough.
