### ISSUE TITLE
Bug: incorrect error from failed ticket validation

### ISSUE THREAD

**Issue by hannahwoodward** [verbb/Events#54]
### Description
I'm programatically creating Events (and setting tickets). It fails trying to save the element, which I narrowed down to the ticket failing validation, with the error "Ticket type must be set.".

However, the ticket type id was set, and the error message in the Event ticket validation doesn't report the actual validation issue (which in my case was a duplicate SKU) - 
https://github.com/verbb/events/blob/a6ad80f298f7dc4510b7e236da10306ebb3b75cc/src/elements/Event.php#L251

### Additional info

- Plugin version: 1.4.2
- Craft version: 3.4.9

**Comment by engram-design** [comment]
Good pickup here, fixed in [1.4.3](https://github.com/verbb/events/releases/tag/1.4.3)
