### ISSUE TITLE
Does events work with both commerce and commerce lite?

### ISSUE THREAD

**Issue by terryupton** [verbb/Events#56]
### Description
A general question, as I am researching options for a website I am building for a tuition company.
Events looks like a good fit, as they offer one-off courses and mock-exams they want to make purchasable online. 
However, I suspect they would only need the lite commerce package.
So does events work with both?

**Comment by engram-design** [comment]
Yep, Events works with both versions

**Comment by engram-design** [comment]
This has also been added to the docs, product page and readme - https://verbb.io/craft-plugins/events/features
