### ISSUE TITLE
Events Field Type

### ISSUE THREAD

**Issue by johnj24** [verbb/Events#57]
This might be a feature request, but is there any way currently to relate an entry to an event? We have a news/press release section on a website that can often relate to an event in our event directory. Right now we're using Solspace Calendar to hold our events and they have a field type where we can relate a Solspace Calendar Event to an entry.

**Comment by engram-design** [comment]
There is an Events field you can use. You can also include custom fields to relate anything to an events (even another event).

**Comment by johnj24** [comment]
Thanks, Josh. Initially I didn't see it in the docs and when I scanned the fieldtype dropdown I didn't see it, so my apologies for not looking closer. I found it a few days after I asked and then closed the issue.
