### ISSUE TITLE
Project config crash on merge

### ISSUE THREAD

**Issue by fordchristopher** [verbb/Events#59]
### Description

I would like to report the following issue with Events (https://plugins.craftcms.com/events).

Good afternoon,

I am writing to report a crash with this plugin.  I was following our normal development process, in which I create a development branch, do my development, and then merge with a local, up-to-date master branch.  When I went to merge into my master branch, I ran the following commands:

```
./craft migrate/all 
./craft project-config/sync
```

upon syncing the project config, I received the following error:

```
Applying changes from project.yaml ... error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'event' for key 'tb_events_eventtypes_handle_unq_idx'
The SQL being executed was: INSERT INTO `tb_events_eventtypes` (`uid`, `name`, `handle`, `hasTitleField`, `titleLabel`, `titleFormat`, `hasTickets`, `icsTimezone`, `icsDescriptionFieldHandle`, `icsLocationFieldHandle`, `fieldLayoutId`, `dateCreated`, `dateUpdated`) VALUES ('e138e5af-ad5e-42a7-bab0-285bed545b39', 'Event', 'event', 1, 'Title', '', 1, '', '', '', 75, '2020-05-06 16:56:09', '2020-05-06 16:56:09')
```

I made sure before running the commands that the database did not have that entry, let alone even the table.  It seems like it is trying to add it twice.

### Steps to reproduce

1. Created new branch for development on multi-lanuage site.
2. Merged code to master
3. From directory root ran
```
./craft migrate/all 
./craft project-config/sync
```

### Additional info

- Plugin version: 1.4.7
- Craft version: 3.4.16

**Comment by engram-design** [comment]
Were you performing a plugin or Craft update? If so, can you recall what version's they were from?

**Comment by fordchristopher** [comment]
Hi @engram-design, I was not.  After setting up the plugin, creating an event type, ticket type and a few events on my development branch, I was just trying to merge to master, where the plugin was not installed

**Comment by fordchristopher** [comment]
My workaround for this was to create the event type on the server, re-clone the repository and then copy in my template and other changes so that part of the yaml file did not have to sync.. thanks!
