### ISSUE TITLE
Events saving per site bug after 1.4.10 patch

### ISSUE THREAD

**Issue by fordchristopher** [verbb/Events#60]
### Description

Just updated to 1.4.10 to get the multi-site patch, thanks for releasing.  I think there is still an issue though.

I have three sites on my craft install: English, Spanish and Korean.  When I go to make an event, I enter the English translation into the English page and save.  It then is visible on all three sites.  Now, if I head to the Korean page and enter my other translation and save, I lost the Korean translation and it is replaced with the English translation, and on the English page I have the Korean translation.  I can then overwrite the english translation to its desired text, but I still do not have the korean translation on the korean site.

### Steps to reproduce

1. Create a craft install with three sites.
2. Create an event with a text field that is translatable per site.
3. Enter text for site 1 and save, then change sites, enter text for site 2 (or 3) and save.
4. Look at the 2nd (or 3rd) site that you just updated.  Notice it is different than what was just entered.
5. Also note the difference on the first site.

### Additional info

- Plugin version: 1.4.10
- Craft version: 3.4.16

Thank you!

**Comment by engram-design** [comment]
Strange, I'm not seeing that behaviour, I took a video just to be sure - can you confirm I'm doing everything the same to you?

https://d.pr/free/v/SCaUGQ

**Comment by fordchristopher** [comment]
Yeah that looks right! weird.. Could it be that events created before the update have issues by any chance?  I re-cloned my repo and tried a new event and this time, it worked.  But, when I try it on an existing event, I get an exception
`Attempting to save an element in an unsupported site.`
All I did to get this was go into an event created before the update was installed and try to save anything to one of the sites that doesn't appear first.

**Comment by engram-design** [comment]
Ah gotcha, could you give [1.4.11](https://github.com/verbb/events/releases/tag/1.4.11) a go?

**Comment by fordchristopher** [comment]
That did the trick, thanks again for your help @engram-design!
