### ISSUE TITLE
Is it possible to create an event from a front-end form or a custom module / plugin?

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/Events#62]
The need comes from wanting to set-up recurring events, and allow logged-in users to create events from a front-end form... is it possible at all to hook in the events creation methods?

**Comment by engram-design** [comment]
There's nothing in particular stopping you from putting a POST submission together, and submitting it to `events/events/save`. There's no guide for it at the moment, as it'd be a little involved (essentially replicating the behaviour in the control panel).

If you're interested in having a go at this yourself, check out the [template](https://github.com/verbb/events/blob/craft-3/src/templates/events/_edit.html) that's used in the control panel, taking note of the inputs' `name` attribute.

For starters:

```
{% set eventType = craft.events.getEventTypeById(1) %}

<form>
    <input type="hidden" name="action" value="events/events/save">
    <input type="hidden" name="typeId" value="{{ eventType.id }}">

    <input type="text" name="title" value="New Event">

    {% for field in eventType.getFieldLayout().getFields() %}
        {{ field.name }}: <input type="text" name="{{ field.handle }}">
    {% endfor %}

    <input type="date" name="startDate">
    <input type="date" name="endDate">
```

**Comment by bleepsandblops** [comment]
Thank you for the pointers, appreciate it!
