### ISSUE TITLE
Migration error from 1.3.2 => 1.4.12 on Craft 3.5.4

### ISSUE THREAD

**Issue by sjcallender** [verbb/Events#64]
**Description**
Running an update from Events 1.3.2 to 1.4.12 fails on migration. This build is running on Postgres.

````
Yii Migration Tool (based on Yii v2.0.36)

    > add column icsTimezone string to table {{%events_eventtypes}} ... done (time: 0.001s)
    > add column icsDescriptionFieldHandle string to table {{%events_eventtypes}} ... done (time: 0.000s)
    > add column icsLocationFieldHandle string to table {{%events_eventtypes}} ... done (time: 0.001s)
    > alter column dateCreated in table {{%events_eventtypes}} to datetime NOT NULL AFTER icsLocationFieldHandle ...Exception: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "AFTER"
LINE 1: ...pes" ALTER COLUMN "dateCreated" TYPE timestamp(0) AFTER icsL...
                                                             ^
The SQL being executed was: ALTER TABLE "events_eventtypes" ALTER COLUMN "dateCreated" TYPE timestamp(0) AFTER icsLocationFieldHandle, ALTER COLUMN "dateCreated" DROP DEFAULT, ALTER COLUMN "dateCreated" SET NOT NULL (/Users/stephencallender/Projects/_sites/local-fti/vendor/yiisoft/yii2/db/Schema.php:677)
````

**Steps to reproduce**
1. `./craft update events`

**Additional info**
- Plugin version: 1.32 => 1.4.12
- Craft version: 3.5.4
- Commerce version: 3.2.2.1
- Multi-site: No

**Additional context**
I believe this error has existed prior to us updating Craft to 3.5.

**Comment by engram-design** [comment]
Should be fixed in [1.4.13](https://github.com/verbb/events/releases/tag/1.4.13). Looks like Postgres doesn't really like moving columns around like MySQL does.

Either way, this is honestly a cosmetic thing for older installs, so happy to have it conditional.
