### ISSUE TITLE
Ability for default event times & capacity config

### ISSUE THREAD

**Issue by dr-codswallop** [verbb/Events#67]
Ability to add pre-filled event times configuration. For example if 99% of events always begin at 8pm. Could extend this also to default end time or default event length. And also a default event capacity. This would be useful for seated venues.

Maybe some extra optional parameters in config/events.php?

`'defaultStartTime' => '20:00'`

`'defaultEndTime' => '23:00'` or `'defaultEventLength' => '3hrs'`

`'defaultEventCapacity' => '320'`

**Comment by engram-design** [comment]
Good suggestion, I'll add that to the list!

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
