### ISSUE TITLE
Creating new events from a frontend form 

### ISSUE THREAD

**Issue by JoshC96** [verbb/Events#69]
**What are you trying to do?**
Creating ticket per crawf's suggestion on discord: this is an extension of issue #62 - 
I would like to create an event from a frontend form for authorized users to create a new event. Preferrably (and perhaps making it easier) they would select from a premade list of Event and Ticket Types created by admins with a set list of params which they would fill out. Things like price, event capacity, accessibility, age restrictions etc.

**What's your proposed solution?**
As mentioned in issue #62 it seems possible to recreate a POST request and essentially [duplicate the events edit template from the CP](https://github.com/verbb/events/blob/craft-3/src/templates/events/_edit.html) however thius laso requires access to ticket fields like:
```
{% namespace 'tickets[' ~ ticketId ~ ']' %}
    {% include 'events/_includes/ticket-row' %}
{% endnamespace %}
```

Without pretending I know everything about the plugin, it looks like sending a post request and having actionSave() in the EventsController run with populateEventFromPost $event = EventHelper::populateEventFromPost() does what we're after. 

For a frontend form the ticket types might need a JS solution to have the type selected and then quantity, price, dates etc. Not sure yet about how to cover this one. 

**Additional context**
Attempting to create a platform for events at multiple locations across SA. To have events requested then manually added by admins will be a lot of data entry. Hoping to scale to Aus wide events, automatic event creation with custom validation is super necessary.

**Comment by JoshC96** [comment]
Update: the below will create a new event from the frontend, which is awesome but I'm still tackling the issue of adding tickets, not really sure where to start with that. 

```
  <body>
    {% set eventType = craft.events.getEventTypeById(1) %}
    <form id="form-submission">
      <input type="hidden" name="action" value="events/events/save">
      <input type="hidden" name="typeId" value="1">
      {{ csrfInput() }}

      <input type="text" name="title" value="New Event">

      {% for field in eventType.getFieldLayout().getFields() %}
          {{ field.name }}: <input type="text" name="{{ field.handle }}">
      {% endfor %}

      <input type="date" name="startDate">
      <input type="date" name="endDate">

      <input type="submit" name="" value="send">
    </form>

    <script type="text/javascript">
      $(document).ready(function(){

        $("#form-submission").on("submit", function(e){
          e.preventDefault();

          var formEl = new FormData($(this)[0]);

          $.ajax({
            url: $("input[name='action']",this).val(),
            type: 'post',
            method: "post",
            processData: false,
            contentType: false,
            data: formEl,
            complete: function(o){
              console.log("Complete");
              console.log(o);
            }
          });


        })

      })
    </script>


  </body>
```

**Comment by engram-design** [comment]
Sorry, I should've mentioned you can do this only for authorised users. I was thinking if you wanted guests to be able to create events - that's not possible.

So the tickets are probably the only real complication. You'll need to setup some JS to create multiple tickets, and a button to add or remove them - depending on your needs.

What the CP-based event template does is generate the following (I've simplified it greatly to just show the required inputs:

```
<input type="hidden" name="tickets[new1][typeIds]" value="">
<input type="text" name="tickets[new1][quantity]" placeholder="eg. 100">
<input type="text" name="tickets[new1][price]" placeholder="eg. 10.00">
```

The `new1` key would increment by one for each additional ticket, so `new2`, etc. So if you press a button, it'll need to add these inputs with the correct key. If you want to include custom fields, thats similar:

```
<input type="text" name="tickets[new1][fields][plainText]">
```

So, if you can provide your content in this structure, you should be sorted.

**Comment by JoshC96** [comment]
Ah okay, that makes sense. 
Thank you very much :)
