### ISSUE TITLE
[Feature request] Make tickets optional

### ISSUE THREAD

**Issue by KatieMFritz** [verbb/Events#7]
I'd love to use this to completely replace Solspace Calendar, instead of using both. However, we'll definitely have events where we don't have tickets or don't know ticket details (for example, a calendar of industry events). It would be cool to have the option on an event type or individual event basis to not include tickets. 

I'm pretty sure this and #8  are the main features Events is lacking compared to Calendar, at least where we're concerned.

What's the likelihood you'd be able to incorporate this in the next month or so? Trying to figure out whether we have to continue using both plugins or we can drop Calendar.

**Comment by engram-design** [comment]
Yep, we've been wanting to expand things a little more now we're on Craft 3, and this makes sense. It'll require a bit of work, but I think its something we can achieve in a month or so.

**Comment by engram-design** [comment]
Added in [1.1.0](https://github.com/verbb/events/releases/tag/1.1.0)

**Comment by KatieMFritz** [comment]
Josh, you're a hero.

**Comment by KatieMFritz** [comment]
Just tested it out, and it works great! If you're so inclined for a future release, and you don't foresee problems for other use cases, it would be cool to be able to enable/disable tickets per event type, so the tickets tab doesn't even show up for some event types.

**Comment by engram-design** [comment]
Now that you mention it, I had that incorporated a long time ago, but its gone away. Will add it the next release.

**Comment by sjcallender** [comment]
@engram-design Would you be able to make room for this sometime this month?

**Comment by engram-design** [comment]
@KatieMFritz Have now added this setting to event types in [1.1.7](https://github.com/verbb/events/releases/tag/1.1.7)
