### ISSUE TITLE
Support for Multiple Venues/Locations/Organizations

### ISSUE THREAD

**Issue by we-do** [verbb/Events#70]
A client has multiple venues/locations, each with their own events. They are wanting to have a single "platform" to sell tickets to all their events. Is there any talk of a future iteration being able to support locations or even organizations? Each with their own ticket types and possibly other settings?

Currently they manage an organization account on Eventbrite, within it they can create all their venues, each with their own events. Within each newly created event they set the venue and all the event settings such as ticket types. (Ticket Types on Eventbrite are not global, rather created per event.)

Just curious before we start building something custom. :)

Thanks!

**Comment by engram-design** [comment]
Nothing planned _just_ yet, but I've been giving the concept of "Event Groups" some consideration. The idea being you could group multiple Event Types together, which each have their own events/sessions/tickets.

Right now, you'd have to create multiple Event Types for each organisation:

- Org 1 - General Events
- Org 1 - Occasional Events
- Org 2 - General Events
- ...etc

With the above getting a bit messy - and you loose the ability to have different Event Types within those. Say, if your "General Events" you wanted to have "General Events", but some events need to be special, like "Annual Review", or "Christmas Celebration", etc.

With event groups, this would give you a bit of a visual grouping to keep them seperate. I'd picture this in a similar way to how you use Multi Sites with other content, but you'd never want them propagating across to another event group.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
