### ISSUE TITLE
Displaying events and tickets based on the current user

### ISSUE THREAD

**Issue by kevadamson** [verbb/Events#71]
Sorry for being a dumbass, but what is an example of the twig syntax required for listing event / ticket details based on the current user logged in and what they have purchased?

**Comment by engram-design** [comment]
Have a look at https://verbb.io/craft-plugins/events/docs/getting-elements/event-queries#customer

```
{# Fetch events that have been purchased by a customer #}
{% set events = craft.events.events()
    .customer(craft.commerce.getCarts().getCart().customer)
    .all() %}
```

and https://verbb.io/craft-plugins/events/docs/getting-elements/ticket-queries#customer

```
{# Fetch tickets that have been purchased by a customer #}
{% set tickets = craft.events.tickets()
    .customer(craft.commerce.getCarts().getCart().customer)
    .all() %}
```

**Comment by kevadamson** [comment]
I get "Calling unknown method: craft\commerce\Plugin::getCart()" error ...

**Comment by engram-design** [comment]
Sorry, the docs required updating - I have edited me previous post
