### ISSUE TITLE
Moving attendee (ticket) to a different event

### ISSUE THREAD

**Issue by timkinali** [verbb/Events#72]
**What is the proposed way to transfer a ticket to a different event?**

For the moment, the way we handle it is manually creating new orders with 100% discount, then removing old tickets and adjusting capacity. There's quite a lot of steps involved. Mistakes happen. And the order view gets polluted with these orders that are only there to create new tickets. Is there other alternatives?

It would be great if the plugin could handle this some way. Or if the API allows to create and manipulate tickets we could pehaps build  a custom UI for the admin? Does a ticket always have to be created through an order? 

Context / use case:
We have recurring events. Each date is set up as a separate event. Quite often, customer who purchased a ticket for a specific date (event) contact us, because they want to attend at a later date. Admin needs to be able to move the participant to another event.

**Comment by engram-design** [comment]
So a purchased ticket does always need to be associated with an order, at least for the moment. I think this is something we can get around relatively easy though, as there's no way to just create a purchased ticket.

We'd just need to introduce some smarts to sort out capacity from the old event/ticket to the new event/ticket, as you mention.

**Comment by timkinali** [comment]
Great if this could be sorted out for 2.0.0. 

Note. At least for my client, the most common use case is to move a participant between different dates of the same event. If you introduce the feature to have multiple dates nested in an event, perhaps that could open up possibilities to move tickets among those dates, without the need for a new order? It's like the same product, different color.

Related. The pandemic also have highlighted the need to handle event statuses like: scheduled, cancelled, rescheduled (changed location and/or time). We set up our own solution to this but it could be a nice addition to roll into the product.

**Comment by engram-design** [comment]
Yep, we find that's a pretty common scenario as well (people book a 7pm Saturday event, but need to swap to the 8pm Sunday event). We'll be introducing "sessions" which adds another layer of event data to an actual event, so this'll be somewhat easier - but the feature request still stands, and is very common. I definitely wouldn't want you to create a new order, instead just editing a purchased ticket to change the session/event.

Great point on the session/event statuses.

**Comment by satcreative** [comment]
The scenario that @timkinali states, with recurring events and the need to transfer participants to a later date of the same event is exactly the scenario I am facing.

@engram-design, is there any update/timeframe to the "sessions" functionality you mention or the ability to manually create tickets?

**Comment by engram-design** [comment]
@satcreative No update on ETA, it's a rather large update so will likely be a few months away at the least.

**Comment by RitterKnightCreative** [comment]
Another bump for this.

One of my clients does online trainings and it's common to move one person from one training (on one date) to another (on another date) for whatever reason.   I erroneously thought removing the old item/purchaseable and changing to a new one from Commerce editing screen would do all the magic here but after the order is set, it looks like purchased tickets is locked in. Definitely not intuitive for a client.

**Comment by timkinali** [comment]
Yet a bump for this. It's a major pain to handle. I'm always getting phone calls about this from the client to describe over and over again the hacky steps they need to go through for moving events or tickets. It's very easy to make a mistake and it's not just an inconvenience, it affects their customers experience when tickets are lost, set at wrong date/locations or charged twice.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).

**Comment by timkinali** [comment]
Sorry for writing in a closed thread. Very happy to see the sessions feature has come and is out of beta! Does 3.0 also add the possibility to move persons between dates as discussed in this issue? (I didn't see any mention about it in the release notes) @engram-design

**Comment by engram-design** [comment]
So previously, you couldn't edit any relation information about a purchased ticket (essentially an attendee), but in Events 3 you can. With the introduction of sessions, it's a matter of changing the session in the control panel.

![image](https://github.com/user-attachments/assets/1a4083c4-e823-4ed9-918a-e1e908dfb0cc)

**Comment by timkinali** [comment]
Lovely. Thank you!
