### ISSUE TITLE
Support reordering tickets for an event

### ISSUE THREAD

**Issue by Kashkin** [verbb/Events#75]
**What are you trying to do?**
When managing multiple tickets, it's currently not possible to control the order. To "move" a ticket to the top, you would need to delete all tickets above, and recreate them below.

**What's your proposed solution?**
A drag-and-drop interface, like matrix blocks or product variants, would be more consistent and provide a better author experience.

**Additional context**
![Tickets Table](https://user-images.githubusercontent.com/3699310/105281902-0e516180-5bfd-11eb-88a8-2ee51479f59e.png)

**Comment by engram-design** [comment]
Likely bundled with upcoming changes in https://github.com/verbb/events/issues/81 with Event Sessions.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3), events and tickets have been completely reworked!
