### ISSUE TITLE
Support UI Elements in Field Layout for Event Types

### ISSUE THREAD

**Issue by Kashkin** [verbb/Events#76]
**What are you trying to do?**
I'd like to include tips, warnings and custom elements in the event editing screen.

(And maybe even in Tickets? 😜 )

**What's your proposed solution?**
Implement the UI Elements introduced in Craft 3.5

**Additional context**
![UI Elements in Field Layout](https://user-images.githubusercontent.com/3699310/105282051-62f4dc80-5bfd-11eb-87c1-6456d6c50e01.png)

**Comment by benface** [comment]
Also: customized labels! Although they can be set, they don't seem to have any effect at the moment.

**Comment by engram-design** [comment]
I _think_ this should be fairly achievable at the moment.

**Comment by cholawo** [comment]
+1 this would be really helpful for us too

**Comment by anchovy** [comment]
+1 this would be really helpful for us too

**Comment by stevecomrie** [comment]
+1 i was literally just here to recommend something like this.

**Comment by mihob** [comment]
+1 same here!

**Comment by engram-design** [comment]
Added in [2.0.2](https://github.com/verbb/events/releases/tag/2.0.2)
