### ISSUE TITLE
QR Code on PDF ticket to prevent inadvertent checkin

### ISSUE THREAD

**Issue by aeu** [verbb/Events#77]
**What are you trying to do?**
To prevent the user from inadvertently scanning the QR code for the event and being checked in.

A description of what you want to happen.
A protection mechanism to prevent it.

**What's your proposed solution?**
The checkin functionality would only work if a specific user was logged in (staff account of some kind) and if anyone else scanned it in, it would redirect to the event page.

**Additional context**

**Comment by engram-design** [comment]
Yep, I'm thinking we provide an option to auto-checkin the user as soon as they hit that URL (as soon as they hit the URL, they're checked in).

As another option (probably the new default), the user will need to click a "Check In" button on the resulting URL.

The reason for the aut-checkin at the moment is for speed, when people are scanning tickets at the door, saving a extra tap on their phone to check in.

But I also see the value in setting permission restrictions on who can check in a user, so we'll add a setting for a nominated user group to only allow this. At the moment, it's anonymous (again, for speed and prevent hassles with lots of staff scanning codes without an account.)

**Comment by CaporalJuju** [comment]
We use tickets for events on specific dates. Is it possible to authorize check-in only on the date of the event?

or at least never before that date?

**Comment by engram-design** [comment]
That's probably a good option to add, and we'll probably incorporate an interval or offset value to configure that. At the time of event might be tricky in practice, as people might need to handle VIP tickets that could get in early access.

**Comment by engram-design** [comment]
Updated in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3). The check in template now shows a page to check in, rather than automatically checking in the ticket.
