### ISSUE TITLE
Need to save Event twice to change the name of the ticket in an order when dynamically generating the Event title

### ISSUE THREAD

**Issue by ragnarfrosti** [verbb/Events#78]
We are using the latest version of the Event plugin and have a problem with the name of the ticket on an order when the dynamic title of the event changes.

The event type has a hidden title field and the title is autogenerated by the start date, end date and two other fields (location entry and a course entry)

<img width="1463" alt="Event type title field" src="https://user-images.githubusercontent.com/4622136/109784478-67a0ad80-7c0b-11eb-88e4-859f2b9bfea2.png">

**Steps to reproduce**

1. Create a new event that dynamically generates the title
2. Go to Commerce > Orders > + New order in Craft commerce **Create your first line item** and search for the newly created event there it looks like this:

<img width="1514" alt="New line item" src="https://user-images.githubusercontent.com/4622136/109785070-07f6d200-7c0c-11eb-80ba-52cccd146474.png">

So far so good.

3. Update the dates on the event, or one of the other fields that we use to create the title of the event. (I changed the start date in this example) and do step 2 above where you add a line item to an order and you'll see that the name of the ticket has not been updated.

<img width="1514" alt="New line item" src="https://user-images.githubusercontent.com/4622136/109785070-07f6d200-7c0c-11eb-80ba-52cccd146474.png">

4. Resave the event without changing anything and then it will get the new name (with the correct date) when creating a new order in Craft Commerce

<img width="1509" alt="Screenshot 2021-03-03 at 10 25 05" src="https://user-images.githubusercontent.com/4622136/109785783-c61a5b80-7c0c-11eb-8f05-a3217cc27677.png">

So we always need to save an event twice after changing any of the fields that are used to generate the title of the event.

**Additional info**
- Plugin version: 1.4.15
- Craft version: 3.4.23
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
