### ISSUE TITLE
[Feature request] ICS sharing

### ISSUE THREAD

**Issue by KatieMFritz** [verbb/Events#8]
The Solspace Calendar plugin allows calendars (event types) to be shared/subscribed with ICS. That would be pretty rad to have here. Is that on the roadmap? 😄

**Comment by engram-design** [comment]
Its on the roadmap now! 😄

**Comment by engram-design** [comment]
Just wanted to clarify with this. Are you after creating an ICS file (dynamically) for specific, single events, or for the event type (and all associated events)?

**Comment by KatieMFritz** [comment]
Both! Use cases:

- Add to calendar link for single events
- Subscribe to calendar for event types (individually, or even customize your own calendar by selecting which event types you want)

**Comment by sjcallender** [comment]
@engram-design Would you be able to make room for this sometime this month?

**Comment by engram-design** [comment]
Added in [1.4.5](https://github.com/verbb/events/releases/tag/1.4.5). Refer to [docs](https://verbb.io/craft-plugins/events/docs/template-guides/ics-exporting)
