### ISSUE TITLE
Introduce "Event Sessions"

### ISSUE THREAD

**Issue by engram-design** [verbb/Events#81]
We're wanting to put another layer of content in between an event and a ticket - we're calling it "event sessions".

For example, let's say you have an event "Weekend Concert". This event has 3 sessions over a weekend:

- Saturday 7:30pm
- Sunday 11:00am
- Sunday 8:00pm

Currently, to achieve this, you'd need to create 3 separate events for each session. This ends up with a lot of duplicate content with the event (name, images, location, details, etc)

Each Event will have multiple sessions - default to 1 (for older installs to migrate across). Each session can have multiple tickets, which remain the purchasable.

Alongside a nice UI to handle everything.

Scheduled for 2.0

**Comment by anchovy** [comment]
Hi @engram-design We could definitely use this, any idea when Events 2.0 will be released?
Ideally, each event could still/also have its own custom fields ie. location/description so we could use this for conferences etc.

**Comment by engram-design** [comment]
It'll be a while off yet, as we prioritise Craft 4 support, which will be 2.0 due to the breaking changes in platforms from Craft 3. This'll therefore likely to make it into Events 3. Still aiming for later this year.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
