### ISSUE TITLE
Cannot add ticket to cart

### ISSUE THREAD

**Issue by shoored** [verbb/Events#82]
**Description**
Just setup Events plugin for the first time. Added my Event type and Ticket type. Added first Event and ticket.
When using the example code from the docs (https://verbb.io/craft-plugins/events/docs/template-guides/events-index) adding an event to cart returns the following error :

`Getting unknown property: verbb\events\elements\Ticket::product`

**Steps to reproduce**
1. Add Event and Ticket types
2. Create your first Event and add one ticket type
3. Try to add the ticket to your cart
4. No profit

**Additional info**
- Plugin version: 1.4.16
- Craft version: 3.5.19.1
- Craft Commerce version: 3.2.17.4
- Multi-site: No

**Comment by shoored** [comment]
My custom module with OrderAdjustments is the culprit, sorry. It's expecting a product, not a custom purchasable. Will have to do some refactoring in checking the item purchasable type first somehow.

**Comment by engram-design** [comment]
If it helps, you can use this to determine if the purchasable is an Events Ticket or not https://github.com/verbb/events/blob/craft-3/src/variables/EventsVariable.php#L110-L117
