### ISSUE TITLE
Event Revisions/Drafts

### ISSUE THREAD

**Issue by RitterKnightCreative** [verbb/Events#83]
Not sure if this is possible since Commerce itself doesn't (yet) support them in products but it'd be great to have drafts/revisions of events.

**Comment by engram-design** [comment]
I think it should be feasible, as drafts are something that any element can use. Versioning on the other hand is specific to entries, so a but more work to include.

**Comment by RitterKnightCreative** [comment]
Sounds like the new unified editor in Craft 4 might make things a bit easier in this department?

**Comment by engram-design** [comment]
Indeed! We'll address this is Craft 4.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
