### ISSUE TITLE
More insights in available tickets and purchased tickets

### ISSUE THREAD

**Issue by shoored** [verbb/Events#84]
**Tickets available**
When viewing the Events listing in the control panel, it would be really nice if you could enable a column that shows the "total tickets available" for each event. Currently you have to click through to an event detail page to see the purchased tickets. 

![image](https://user-images.githubusercontent.com/26165948/123757346-2c16a700-d8be-11eb-99cc-bdfff849df71.png)

**Expanded purchased tickets view** 
You can see the purchased tickets in the Purchased tickets overview which is a really nice feature. But it requires some clicking through to get a grasp of what events are selling out quick, for instance. 

I can imagine it differs per project setup how Event titles are generated, but in this case, it does not really tell you at a glance for what specific events the tickets where bought since the titles are pretty generic.

Since this client project in particular has "X tickets left" or "sold out" labels on the front-end, I just tell my client to check there. 

Perhaps in addition, it would be nice to be able to see the purchased tickets as actual rows, on an Event detail page in the control panel. For example:

![image](https://user-images.githubusercontent.com/26165948/123757058-dd690d00-d8bd-11eb-8c6f-c6ec2bc42e47.png)

Just my 2 cents. Hopefully this makes sense and is of value to you and other people.

**Comment by engram-design** [comment]
Appreciate the feedback, all good ideas! As for the purchased tickets summary, that's tricky, as for large events, this would be a **massive** table, so I'm thinking now that purchased tickets are elements, we introduce an element index view here, which is searchable/sortable/paginated. Alongside this, we'll provide some stats such as total sold, total available, total per type, etc.

**Comment by shoored** [comment]
Ah that makes sense. I can imagine the purchased tickets being a really large list of elements for some projects. These all sound like really great additions! Thanks for the quick response. Really appreciated.

**Comment by engram-design** [comment]
Things have been revamped in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3) and there's lots of options to achieve this sort of thing now.
