### ISSUE TITLE
Set table columns on purchased tickets for data export

### ISSUE THREAD

**Issue by richardgrantham26** [verbb/Events#87]
**What are you trying to do?**
Currently when a new event is added we have to specify on each folder to add customer, customer first name and customer last name. It would be great if this could be set once for all events.

Also when we export the data these fields aren't available. It would be very useful for us to have the customer info selected when we export this data.

**What's your proposed solution?**
Add the facility for default table columns across all events that is also added to the export facility

![Screen Shot 2021-08-25 at 4 10 09 pm](https://user-images.githubusercontent.com/3916694/130735873-7953a508-8f10-4a52-b53e-01ea518926b7.png)

**Comment by engram-design** [comment]
Thanks for the FR! What I might suggest is to install and use the [element-index-defaults](https://github.com/verbb/element-index-defaults) plugin, which allows you to set the default element indexes for any element. In [2.0.0](https://github.com/verbb/element-index-defaults/releases/tag/2.0.0) I've just added the ability to define third-party element configurations.

**Comment by engram-design** [comment]
As for the exports, it's something the Events plugin can certainly create, but I feel like this should probably be a Craft change. https://github.com/craftcms/cms/discussions/9758

I'll agree that your client's expectation seems correct that the export would contain what columns they've picked to show in the table. It's come up a few times in the past as well, for Commerce sites and order exports.
