### ISSUE TITLE
Event Name not updating on Purchased Tickets Page

### ISSUE THREAD

**Issue by dwhoban** [verbb/Events#88]
**Description**
When a user changes the title of an event, the left hand filter navigation on the Purchased tickets page is not updated and shows the original title.  Multiple changes do not impact the filter name.

Desired state is that it reflects the correct name of the event as per the event title.

**Steps to reproduce**
1. Create an event
2. Change the title
3. Sell some tickets
4. Purchased tickets filter shows the original event.

**Additional info**
- Plugin version: 1.4.17
- Craft version: 3.3.10
- Multi-site: Yes

**Additional Context**
<img width="1198" alt="Screen Shot 2021-08-31 at 8 18 11 pm" src="https://user-images.githubusercontent.com/5687870/131487990-80044445-b1e9-4614-b4f0-354bd8f5812f.png">
<img width="372" alt="Screen Shot 2021-08-31 at 8 18 23 pm" src="https://user-images.githubusercontent.com/5687870/131488012-0ef4fdc7-1377-49e6-bd39-37ac6ec51a8d.png">

**Comment by engram-design** [comment]
Strange. I can't seem to replicate this, as changing the event name seems to update it for me.

Before the updated title:
![image](https://user-images.githubusercontent.com/1221575/131675118-d43b759f-98fb-463c-b890-1ee4d56bccd2.png)
![image](https://user-images.githubusercontent.com/1221575/131675168-741cc104-a926-4d12-8a2a-d1dfb882a2e7.png)

Renaming the event:
![image](https://user-images.githubusercontent.com/1221575/131675229-0a3c8b83-8c33-4deb-b07c-f3bfec9be245.png)
![image](https://user-images.githubusercontent.com/1221575/131675252-f578253c-219b-4dcc-8f8c-3a5bc634629b.png)

**Comment by dwhoban** [comment]
Super strange -  I think I might have just found it...

<img width="1058" alt="Screen Shot 2021-09-06 at 8 53 26 pm" src="https://user-images.githubusercontent.com/5687870/132206665-ef5e869c-3359-4d3c-8ade-0be53657d3e7.png">

Two entries in the content table which reference the element.  They both also have the the same updated date. But the Site ID is different.

Basically I think its not updating the site 3 - which doesn't have a url or a template attached.

**Comment by dwhoban** [comment]
Confirmed, when I go int the Database and update site 3, it corrects the filter title.

**Comment by engram-design** [comment]
Ah, I see, I should've taken note that it was a multi-site. So that's somewhat of a tricky situation in that events are multi-site enabled, but purchased tickets aren't. This is mostly down to lack of support for Commerce multi-store functionality (not multi-site) which is coming.

I suppose we could add a site dropdown to purchased tickets to handle this, but to make that work, we'd need to record the site the ticket was purchased on, which we currently don't.

**Comment by dwhoban** [comment]
@engram-design sorry took a minute to come back round to this one. Had a chance to step through this one...

1. User then creates an event on the default site
2. Default Site has correct name
![Screen Shot 2021-10-10 at 2 50 55 pm](https://user-images.githubusercontent.com/5687870/136682711-df08d93e-a021-4737-bd95-1c3c2569ce58.png)
3. Secondary site populated with incorrect name
![Screen Shot 2021-10-10 at 2 51 01 pm](https://user-images.githubusercontent.com/5687870/136682721-ac8e03eb-7abb-4cdf-ad7b-4084da1f4d21.png)

**Comment by engram-design** [comment]
Yep, so my comment still applies that purchased tickets aren't site-aware (yet), so we'll add that to our support

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
