### ISSUE TITLE
Pass custom field data to ticket using ticket checkin form

### ISSUE THREAD

**Issue by satcreative** [verbb/Events#89]
**What are you trying to do?**
I want to be able to gather a name and email address for each ticket that is checked in.

**What's your proposed solution?**
I have created 2 custom fields for the ticket type and have added 2 related input fields to the ticket checkin form, however; it's not clear to me how to pass the submitted fields to the ticket entry. Does this functionality already exist?

**Additional context**
Below is the checkin form template I currently have:

```
<form method="post" accept-charset="UTF-8">
      <input type="hidden" name="action" value="events/ticket/checkin">
       {{ csrfInput() }}
      <input type="text" name="fields[delegateName]">
      <input type="email" name="fields[delegateEmail]">
      <input type="text" name="sku">
      <input type="submit" value="Check in to event">
 </form>
```

**Comment by engram-design** [comment]
At the moment, checking in a ticket doesn't do a full update of the element, mostly for speed. It takes slightly longer to save an element than it does to save a purchased ticket record, which is important when trying to check customers in with speed. We'd need to save the full element to save the custom field values.

One option you have is to save the purchased ticket yourself, but you do loose out some of the validation the `events/ticket/checkin` controller provides.

```
<form method="post" accept-charset="UTF-8">
    <input type="hidden" name="action" value="events/purchased-tickets/save">
    <input type="text" name="id" value="{{ purchasedTicket.id }}">
    <input type="text" name="checkedIn" value="true">
    <input type="text" name="checkedInDate" value="{{ now | date('c') }}">
    {{ csrfInput() }}

    <input type="text" name="fields[delegateName]">
    <input type="email" name="fields[delegateEmail]">
    <input type="text" name="sku">
    <input type="submit" value="Check in to event">
</form>
```

Here, we're setting the `checkedIn` and `checkedInDate`.

**Comment by satcreative** [comment]
Thanks for the work around, @engram-design.

I've changed the form action to `events/purchased-tickets/save` as you suggest and have been able to save the data to the custom fields, however; the `checkedIn` and `checkedInDate` fields aren't having any effect on checking the ticket in. 

Are the below fields correct:
```
<input type="text" name="checkedIn" value="true">
<input type="text" name="checkedInDate" value="{{ now | date('c') }}">
```
Below is a screenshot of the ticket in the backend after using the save ticket form:

![Screenshot 2021-09-01 at 14 29 18](https://user-images.githubusercontent.com/12640985/131681170-eb816548-171d-4f32-b56c-92c996b35373.png)

**Comment by engram-design** [comment]
Actually, great point - this won't apply that content. I've just updated that to work now.

In addition, I've also made a change to `events/purchased-tickets/checkin` to support saving custom fields. So if you wanted to go back to your original code, just update the endpoint to `events/purchased-tickets/checkin` and ensure you supply an `id` for the purchased ticket, and that'll automatically checkin with support for custom fields.

```
<form method="post" accept-charset="UTF-8">
    <input type="hidden" name="action" value="events/purchased-tickets/checkin">
    <input type="hidden" name="id" value="{{ purchasedTicket.id }}">
    {{ csrfInput() }}

    <input type="text" name="fields[delegateName]">
    <input type="email" name="fields[delegateEmail]">
    <input type="text" name="sku">
    <input type="submit" value="Check in to event">
</form>
```

Ensure you update to [1.4.18](https://github.com/verbb/events/releases/tag/1.4.18)

**Comment by satcreative** [comment]
Perfect! Thanks for adding that @engram-design.
