### ISSUE TITLE
[bug] Field Labels plugin not saving for event type field setup

### ISSUE THREAD

**Issue by KatieMFritz** [verbb/Events#9]
I'm using the [Field Labels plugin](https://github.com/spicywebau/craft-fieldlabels) (similar to Relabel) to override the label and instructions of some fields in my event types.

Everything looks fine while editing, but after I save the event type, the changes get wiped and I'm back to my original field labels and instructions.

## Setup:

- Craft Pro 3.1.26
- PostgreSQL 10.7
- Events 1.0.2.1
- Field labels 1.1.0

**Comment by engram-design** [comment]
Looks like the Field Labels plugin is opt-in. Please see [PR #32](https://github.com/spicywebau/craft-fieldlabels/pull/32)
