### ISSUE TITLE
Maximum and minimum purchasable quantity of ticket per customer or guest cart

### ISSUE THREAD

**Issue by stephano41** [verbb/Events#91]
Similar to how Craft Commerce allows for a maximum and minimum quantity that a customer can buy, it would be great if this was a feature in Events as well, meaning that it is possible to limit how many tickets are bought.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
