### ISSUE TITLE
Discount can't be applied to Event/Ticket via a Category condition

### ISSUE THREAD

**Issue by peteeveleigh** [verbb/Events#92]
When setting up a Discount code it's possible to only apply it to matching items. One way to define these matches is via a category.

I have created a category called "Discount allowed" and assigned my event to it.
I have created a discount code that matches the category "Discount allowed".

When I add a ticket for the event to the basket, and add the code, no discount is applied.

If, instead, I use a matching condition for the Event itself then the discount is applied.

Although that's a temporary work around for us, we have a lot of events. And it would be far simpler for the admin to simply add the event to a category rather than have to remember to go and add the event to every discount code that's running.

**Additional info**
- Plugin version: 1.4.19.2
- Craft version: 3.7.16
- Commerce version: 3.4.5
- Multi-site: No

**Comment by engram-design** [comment]
That's correct, you can't select the event, or event type to be applied to a discount. Instead, Commerce only allows to apply the purchasable - in this case the ticket - to the discount.

In a similar way, you can't select the Product Type to apply a discount by, in core Commerce, which would be handy, and similar to what you're wanting (the wrapper around products/events).

When you mention `matching condition for the Event itself` do you mean using the "Order Condition Formula" settings?

We'd need to get Commerce to add events for us to provided "Matching Options" to handle this better.
