### ISSUE TITLE
Seating Areas with pooled ticket capacity & seperate pricing

### ISSUE THREAD

**Issue by neokoenig** [verbb/Events#98]
I'd like to setup something whereby:

An event has multiple seating areas, i.e
 - Seating Area A (100 seats)
 - Seating Area B (50 seats)
 - Seating Area C (25 seats)

Each seating area has it's own capacity, independent of the event's capacity (or rather, instead of).
And each seating area can have multiple ticket types, which have their own price. There then might be the capacity for an additional ticket type with no restrictions, i.e to purchase streaming access.

So the end result might be:

 - Seating Area A (100 tickets available)
    - Standard Ticket ($30)
    - Concession Ticket ($20)
    - Premium Ticket ($50)
 - Seating Area B (50 tickets available)
    - Standard Ticket ($20)
    - Concession Ticket ($15)
 - Seating Area C (25 tickets available)
    - Standard Ticket ($15)
    - Concession Ticket ($10)
 - Streaming Access only (no restriction on no. of tickets)
    - Streaming Ticket ($5)

I'm pretty this isn't do-able "out the box", but is it hypothetically do-able?
Thanks!

**Comment by engram-design** [comment]
Not at the moment but will be with "sessions" https://github.com/verbb/events/issues/81. This adds the layer between an event and a ticket, which you describe well here.

The only real solution at the moment is to make each seating area its own event, which is likely not very ideal, and lacks the grouping needed at scale (if you have more than a handful of events)

**Comment by stuh** [comment]
@neokoenig we did something similar to create a sessions setup where we had multiple sessions related to the same event.

As Josh describes make each seating area an event of its own with the required ticket breakdown. Give each of these events an Entries field which relates back to an Entry.

On the Entry's page you can then query and list the related Events (seating areas) and their tickets. 

It works well for us as it allows us to add supporting content at the Entry level which is the same for all of the' events'.

HTH

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3) with the introduction of sessions in events.
